{
 "title": "Loki NGINX Service Mesh - Pattern version",
 "description": "Loki v2+ showcase using regular NGINX access logs.",
 "tags": [ "ds-example" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "adhoc" },
   { "name": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "KPI's",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({}[$__interval]))  ",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Requests per HTTP status code",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <response_time>` | status != \"\" and status != `\"-\"` | __error__=\"\" [$__interval]))",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "NGINX logs in bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({}[$__interval])",
     "legendFormat": "$label_value"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <response_time>` | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "📊 Dashboard created by Ward Bekker (hope you like it!)\n\n🐦 Follow me on [Twitter](https://twitter.com/wardbekker) & [LinkedIn](https://www.linkedin.com/in/wardbekker/) for  Grafana Loki updates \n\n🎥 Check out my [Grafana Loki video's](https://www.youtube.com/playlist?list=PLDGkOdUX1UjqEzcxQrbROMy8DN7MZv_h4) on Youtube"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <response_time>` |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "# NGINX log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({}[$__interval])"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <response_time>` | status >= 500 |__error__=\"\"[$__interval])) / (sum(count_over_time({} [$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({} |= \"Googlebot\")[$__interval])) / (sum(count_over_time(({} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Requests per Country",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <response_time> <geoip_country_code>` | __error__=\"\" [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 10 },
   "targets": [
    {
     "expr": "topk(10, sum by (geoip_country_code) (count_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <response_time> <geoip_country_code>` | geoip_country_code != \"-\" | geoip_country_code != \"\" and  __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Request statistics over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <request_time> <geoip_country_code>` | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({}  | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <request_time> <geoip_country_code>` | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <request_time>` |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <request_time>` | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Acquisition and Behaviour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_referer) (count_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<http_referer>\" \"<user_agent>\" <response_time> <geoip_country_code>` | http_referer != \"-\" and http_referer != \"\" and http_referer !~ \".*?$host.*?\" and http_referer !~ \".*?\\\\*\\\\*\\\\*.*?\" | __error__=\"\" [15m])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top 10 User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by (user_agent) (count_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <request_time>` |  __error__=\"\" [15m])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_addr, geoip_country_code) (count_over_time({} | pattern `<remote_addr> - - <ts> \"<method> <path> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <response_time> <geoip_country_code>` |  __error__=\"\" [15m])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 38 },
   "targets": [
    {
     "expr": "topk(10, sum by (request_uri) (count_over_time({} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml`  | pattern `<remote_addr> - - <ts> \"<method> <request_uri> <_>\" <status> <body_bytes_sent> \"<_>\" \"<user_agent>\" <response_time>` | status = 200 and request_uri != \"/\" | __error__=\"\" [15m])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  }
 ]
}