{
 "title": "The Four Golden Signals",
 "tags": [ "demo" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(statsd.fakesite.timers.ads_timer.upper_50, 5), 'OK')"
    },
    {
     "target": "alias(movingAverage(statsd.fakesite.timers.ads_timer.upper_25, 5), 'Errors')"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(apps.backend.backend_01.counters.requests.count, 1), 'Requests/s')"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(apps.fakesite.web_server_01.counters.request_status.{code_500,code_400}.count, 5)"
    }
   ]
  },
  {
   "title": "SATURATION",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(apps.fakesite.web_server_01.counters.request_status.code_200.count, 0.3), 'DB CPU')"
    }
   ]
  }
 ]
}