{
 "title": "Prometheus templating",
 "tags": [
  "prometheus",
  "promcon"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobs", "query": "label_values(job)" },
   { "name": "disk_series", "query": "metrics(node_disk)" },
   {
    "name": "query",
    "query": "query_result(up{job=~\"$jobs\"})"
   },
   {
    "name": "instance",
    "query": "up{job=~\"$jobs\"}"
   },
   {
    "name": "instance2",
    "query": "label_values(up{job=~\"$jobs\"}, instance)"
   },
   {
    "name": "last",
    "query": "label_values(up{instance=~\"$instance\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "job=~\"$instance\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "job=~$jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"$jobs\"}",
     "legendFormat": "{{job}} "
    }
   ]
  },
  {
   "title": "$disk_series{job=~\"$jobs\"}",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$disk_series{job=~\"$jobs\"}"
    }
   ]
  }
 ]
}