{
 "title": "Stats Installs",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Installs",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "consolidateBy(summarize(grafana.usagestats.all.reports.count, '24h', 'sum', false), 'max')"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "removeAboveValue(consolidateBy(summarize(grafana.usagestats.all.stats.users.count, '24h', 'sum', false), 'max'), 20000000)"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "removeAboveValue(consolidateBy(summarize(grafana.usagestats.all.stats.active_users.count, '24h', 'sum', false), 'max'), 8000000)"
    }
   ]
  },
  {
   "title": "Alert rules",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "consolidateBy(summarize(grafana.usagestats.all.stats.alerts.count, '24h', 'sum', false), 'max')"
    }
   ]
  },
  {
   "title": "Starred dashboards",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "consolidateBy(summarize(grafana.usagestats.all.stats.stars.count, '24h', 'sum', false), 'max')"
    }
   ]
  },
  {
   "title": "Library panels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "removeAboveValue(consolidateBy(summarize(grafana.usagestats.all.stats.library_panels.count, '24h', 'sum', false), 'max'), 12000000)"
    }
   ]
  }
 ]
}