{
 "title": "Alerting",
 "tags": [ "demo" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Metric Req/s Peaking",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(apps.backend.backend_01.counters.requests.count, 1), 'req / s')"
    }
   ]
  },
  {
   "title": "API Error  / 1min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(summarize(prod.grafana.play.api.response_status_total.code.404.count, '1min', 'sum', 'false'), 'req / s')"
    }
   ]
  },
  { "type": "alertlist", "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Request Time Average < 190ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(statsd.fakesite.timers.ads_timer.upper_50, '5min'), 'request time average')"
    }
   ]
  },
  {
   "title": "Dashboard loads / 1min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(summarize(apps.backend.backend_01.counters.requests.count, '1min', 'sum', false), 'Dashboard loads / min')"
    }
   ]
  }
 ]
}