{
 "title": "InfluxDB Table",
 "tags": [ "influxdb" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mixed data sources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Elasticsearch Series",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "@metric:cpu",
     "timeField": "@timestamp"
    },
    {
     "alias": "InfluxDB Series",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "logins.count",
     "query": "SELECT mean(\"value\") FROM \"logins.count\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "target": "alias(apps.backend.backend_01.counters.requests.count, 'Graphite Series')"
    }
   ]
  },
  {
   "title": "Influx Table",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@hostname", "id": "2", "settings": { "order": "asc", "orderBy": "_term", "size": "0" }, "type": "terms" }
     ],
     "groupBy": [
      { "params": [ "datacenter" ], "type": "tag" }
     ],
     "measurement": "logins.count",
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@hostname", "id": "2", "settings": { "order": "asc", "orderBy": "_term", "size": "0" }, "type": "terms" }
     ],
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "logins.count",
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Influx Table with time series aggregation",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@hostname", "id": "2", "settings": { "order": "asc", "orderBy": "_term", "size": "0" }, "type": "terms" }
     ],
     "measurement": "logins.count",
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@hostname", "id": "2", "settings": { "order": "asc", "orderBy": "_term", "size": "0" }, "type": "terms" }
     ],
     "measurement": "logins.count",
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Influx Table with aggregation and hidden time column",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@hostname", "id": "2", "settings": { "order": "asc", "orderBy": "_term", "size": "0" }, "type": "terms" }
     ],
     "measurement": "logins.count",
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Graph",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "logins.count",
     "query": "SELECT max(\"value\") FROM \"logins.count\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "payment.started",
     "query": "SELECT max(\"value\") FROM \"logins.count\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Summary table",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "logins.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "payment.started",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}