{
 "title": "Graphite sumSeries AliasByNode",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Graphite issue?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeries(apps.backend.*.counters.requests.count), 2)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(carbon.agents.*.cpuUsage),'CPU')"
    }
   ]
  },
  {
   "title": "Points Per Update",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(carbon.agents.*.pointsPerUpdate), 'Points Per Update')"
    }
   ]
  }
 ]
}