{
 "title": "Advanced Layout",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Carbon Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.updateOperations),\"Updates\") "
    },
    {
     "target": "alias(sumSeries(carbon.agents.*.metricsReceived),'Metrics Received')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.*.committedPoints),'Committed Points')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.*.creates),'Creates')"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "apps.backend.backend_01.counters.requests.count"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "apps.backend.backend_01.counters.requests.count"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "apps.backend.backend_01.counters.requests.count"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "apps.backend.backend_01.counters.requests.count"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "apps.backend.backend_01.counters.requests.count"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "apps.backend.backend_01.counters.requests.count"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(carbon.agents.*.cpuUsage),'CPU')"
    }
   ]
  },
  {
   "title": "Points Per Update",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(carbon.agents.*.pointsPerUpdate), 'Points Per Update')"
    }
   ]
  }
 ]
}