{
 "title": "Dashboard with dropdowns",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "request_method", "query": "GET,POST,PUT" },
   { "name": "agent", "label": "UserAgent contains" },
   { "name": "remote_addr" },
   { "name": "status", "query": "200,301,304,404,406,500" }
  ]
 },
 "panels": [
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/nginx/json_access.log\"} | json | (request_method =~ \"$request_method\" or http_user_agent =~ \".*$agent.*\" or status =~ \"$status\") and remote_addr = \"$remote_addr\"  |  __error__=\"\""
    }
   ]
  },
  {
   "title": "UserAgent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (http_user_agent) (count_over_time({filename=\"/var/log/nginx/json_access.log\"}[5m] | json | http_user_agent =~ \".*$agent.*\")) > 5"
    }
   ]
  },
  {
   "title": "Http status code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=\"/var/log/nginx/json_access.log\"}[1m] | json | status =~ \"$status\"))"
    }
   ]
  }
 ]
}