{
 "title": "MLT Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_target)(rate(traces_spanmetrics_latency_sum{http_target=~\"\\\\w+\"}[1m]) / rate(traces_spanmetrics_latency_count{http_target=~\"\\\\w+\"}[1m])) * 55",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Overall Error %age",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\"}[1m]))/sum(increase(traces_spanmetrics_calls_total[1m]))) * 100"
    }
   ]
  },
  {
   "title": "Error Percentages by Target",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (http_target)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",http_target=~\"\\\\w+\"}[1m])))/(sum by (http_target)(increase(traces_spanmetrics_calls_total{status_code!=\"\",http_target!=\"\\\\w+\"}[1m]))) * 100",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Top 10 Highest Endpoint Latencies Over Last Minute",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by (http_method,http_target)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\"\\\\w+\"}[1m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\"\\\\w+\"}[1m])))"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies in ms (Last 10 mins)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "sum by (http_method,http_target)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\"\\\\w+\"}[10m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\"\\\\w+\"}[10m]))",
     "legendFormat": "{{http_target}}: {{http_method}}"
    }
   ]
  },
  {
   "title": "95th Percentile Response Latencies (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mythical_request_times_bucket{beast=~\".*\"}[15s])) by (le, beast))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Autologged Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{job=\"agent\"} | logfmt | status=\"STATUS_CODE_ERROR\""
    }
   ]
  }
 ]
}