{
 "title": "Empty Variables Demo - Postgres",
 "description": "Dashboard which shows current outages from Nodes, Interfaces and Services in selected Surveillance Categories.",
 "tags": [ "opennms" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Monitoring Location",
    "query": "SELECT DISTINCT(n.location) FROM node n ORDER BY location ASC"
   },
   {
    "name": "category",
    "label": "Surveillance Category",
    "query": "SELECT 'no category'::TEXT as categoryname UNION SELECT categoryname FROM categories ORDER BY categoryname"
   }
  ]
 },
 "panels": [
  {
   "title": "Outstanding Business Service Alarms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Node Alarms in Category: $category",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  bsm_service.name,\n  bsmAlarm.firsteventtime,\n  bsmAlarm.lasteventtime,\n  EXTRACT(DAYS FROM age(now(), bsmAlarm.firsteventtime)) || 'd ' || EXTRACT(HOURS FROM age(now(), bsmAlarm.firsteventtime)) || 'h ' || EXTRACT(MINUTES FROM age(now(), bsmAlarm.firsteventtime)) || 'm ' || ROUND(EXTRACT(SECONDS FROM age(now(), bsmAlarm.lasteventtime))::NUMERIC,0) || 's' AS duration\nFROM\n  bsm_service\nJOIN\n  (SELECT\n    substring(reductionkey from '[0-9]+$')::INTEGER AS bsmId,\n    alarms.firsteventtime,\n    alarms.lasteventtime\n  FROM\n    alarms\n  WHERE\n    eventuei = 'uei.opennms.org/bsm/serviceProblem') AS bsmAlarm\nON\n   bsmAlarm.bsmId = bsm_service.id\nORDER BY\n  bsmAlarm.lasteventtime DESC,\n  duration DESC,\n  bsm_service.name ASC"
    }
   ]
  },
  { "title": "Outstanding Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Node Alarms in Category: $category",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  node_alarms.location,\n  node_alarms.nodelabel,\n  node_alarms.lasteventtime,\n  to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime AS duration_raw,\n  EXTRACT(DAYS FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime) || 'd ' || EXTRACT(HOURS FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime) || 'h ' || EXTRACT(MINUTES FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime) || 'm ' || ROUND(EXTRACT(SECONDS FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime)::NUMERIC,0) || 's' AS duration\nFROM\n  node_alarms\nWHERE\n  node_alarms.acknowledged = FALSE AND\n  node_alarms.eventuei like 'uei.opennms.org/nodes/nodeDown' AND\n  node_alarms.location IN ($location) AND\n  node_alarms.categoryname IN ($category) AND\n  node_alarms.max_alarm_severity_unack = '6'\nGROUP BY\n  node_alarms.location,\n  node_alarms.nodelabel,\n  node_alarms.nodeid,\n  node_alarms.firsteventtime,\n  node_alarms.lasteventtime\nORDER BY\n  duration_raw DESC,\n  node_alarms.location ASC,\n  node_alarms.nodelabel ASC"
    }
   ]
  },
  {
   "title": "Interface Alarms in Category: $category",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  node_alarms.location,\n  node_alarms.nodelabel,\n  node_alarms.ipaddr,\n  node_alarms.lasteventtime,\n  to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime AS duration_raw,\n  EXTRACT(DAYS FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime) || 'd ' || EXTRACT(HOURS FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime) || 'h ' || EXTRACT(MINUTES FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime) || 'm ' || ROUND(EXTRACT(SECONDS FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime)::NUMERIC,0) || 's' AS duration\nFROM\n  node_alarms\nWHERE\n  node_alarms.acknowledged = FALSE AND\n  node_alarms.eventuei like 'uei.opennms.org/nodes/interfaceDown' AND\n  node_alarms.location IN ($location) AND\n  node_alarms.categoryname IN ($category) AND\n  node_alarms.max_alarm_severity_unack = '5'\nGROUP BY\n  node_alarms.location,\n  node_alarms.nodeid,\n  node_alarms.nodelabel,\n  node_alarms.ipaddr,\n  node_alarms.firsteventtime,\n  node_alarms.lasteventtime\nORDER BY\n  duration_raw DESC,\n  node_alarms.location ASC,\n  node_alarms.nodelabel ASC,\n  node_alarms.ipaddr ASC"
    }
   ]
  },
  {
   "title": "Service Alarms in Category: $category",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  node_alarms.location,\n  node_alarms.nodelabel,\n  node_alarms.ipaddr,\n  node_alarms.servicename,\n  node_alarms.lasteventtime,\n  to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime AS duration_raw,\n  EXTRACT(DAYS FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime) || 'd ' || EXTRACT(HOURS FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime) || 'h ' || EXTRACT(MINUTES FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime) || 'm ' || ROUND(EXTRACT(SECONDS FROM to_timestamp($__unixEpochTo()) - node_alarms.firsteventtime)::NUMERIC,0) || 's' AS duration\nFROM\n  node_alarms\nWHERE\n  node_alarms.acknowledged = FALSE AND\n  node_alarms.eventuei like 'uei.opennms.org/nodes/nodeLostService' AND\n  node_alarms.location IN ($location) AND\n  node_alarms.categoryname IN ($category) AND\n  node_alarms.max_alarm_severity_unack = '5'\nGROUP BY\n  node_alarms.location,\n  node_alarms.nodeid,\n  node_alarms.nodelabel,\n  node_alarms.ipaddr,\n  node_alarms.servicename,\n  node_alarms.firsteventtime,\n  node_alarms.lasteventtime\nORDER BY\n  duration_raw DESC,\n  node_alarms.location ASC,\n  node_alarms.nodelabel ASC,\n  node_alarms.ipaddr ASC,\n  node_alarms.servicename ASC"
    }
   ]
  },
  { "title": "Current Outages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Nodes in Category: $category",
   "type": "table-old",
   "description": "Availability for Nodes with outages in a selected Surveillance Category",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  n.location,\n  n.nodelabel,\n  100.0 - 100.0/(EXTRACT(EPOCH FROM to_timestamp($__unixEpochTo())) - EXTRACT(EPOCH FROM to_timestamp($__unixEpochFrom()))) * EXTRACT(EPOCH FROM (to_timestamp($__unixEpochTo()) - GREATEST(n.iflostservice, to_timestamp($__unixEpochFrom())))) AS availability,\n  to_timestamp($__unixEpochTo()) - n.iflostservice AS duration_raw,\n  EXTRACT(DAYS FROM to_timestamp($__unixEpochTo()) - n.iflostservice) || 'd ' || EXTRACT(HOURS FROM to_timestamp($__unixEpochTo()) - n.iflostservice) || 'h ' || EXTRACT(MINUTES FROM to_timestamp($__unixEpochTo()) - n.iflostservice) || 'm ' || ROUND(EXTRACT(SECONDS FROM to_timestamp($__unixEpochTo()) - n.iflostservice)::NUMERIC,0) || 's' AS duration\nFROM\n  node_outages n\nJOIN\n  node_outage_status nos\nON\n  n.nodeid = nos.nodeid\nWHERE\n  n.resolved = FALSE AND\n  n.svclosteventuei = 'uei.opennms.org/nodes/nodeDown' AND\n  nos.max_outage_severity = '6' AND\n  n.categoryname IN ($category) AND\n  n.location IN ($location)\nGROUP BY\n  n.location,\n  n.nodelabel,\n  n.eventseverity,\n  n.iflostservice\nORDER BY\n  duration_raw DESC,\n  availability ASC,\n  n.location ASC,\n  n.nodelabel ASC"
    }
   ]
  },
  {
   "title": "Node Interfaces in Category: $category",
   "type": "table-old",
   "description": "Availability for Interfaces with outages in a selected Surveillance Category",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  n.location,\n  n.nodelabel,\n  n.ipaddr,\n  100.0 - 100.0/(EXTRACT(EPOCH FROM to_timestamp($__unixEpochTo())) - EXTRACT(EPOCH FROM to_timestamp($__unixEpochFrom()))) * EXTRACT(EPOCH FROM (to_timestamp($__unixEpochTo()) - GREATEST(n.iflostservice, to_timestamp($__unixEpochFrom())))) AS availability,\n  to_timestamp($__unixEpochTo()) - n.iflostservice AS duration_raw,\n  EXTRACT(DAYS FROM to_timestamp($__unixEpochTo()) - n.iflostservice) || 'd ' || EXTRACT(HOURS FROM to_timestamp($__unixEpochTo()) - n.iflostservice) || 'h ' || EXTRACT(MINUTES FROM to_timestamp($__unixEpochTo()) - n.iflostservice) || 'm ' || ROUND(EXTRACT(SECONDS FROM to_timestamp($__unixEpochTo()) - n.iflostservice)::NUMERIC,0) || 's' AS duration\nFROM\n  node_outages n\nJOIN\n  node_outage_status nos\nON\n  n.nodeid = nos.nodeid\nWHERE\n  n.resolved = FALSE AND\n  n.svclosteventuei = 'uei.opennms.org/nodes/interfaceDown' AND\n  nos.max_outage_severity = '5' AND\n  n.categoryname IN ($category) AND\n  n.location IN ($location)\nGROUP BY\n  n.location,\n  n.nodelabel,\n  n.iflostservice,\n  n.ipaddr,\n  n.eventseverity,\n  n.svclosteventuei\nORDER BY\n  duration_raw DESC,\n  availability ASC,\n  n.location ASC,\n  n.nodelabel ASC,\n  n.ipaddr ASC\n"
    }
   ]
  },
  {
   "title": "Node Services in Category: $category",
   "type": "table-old",
   "description": "Availability for Services with outages in a selected Surveillance Category",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  n.location,\n  n.nodelabel,\n  n.ipaddr,\n  n.servicename,\n  100.0 - 100.0/(EXTRACT(EPOCH FROM to_timestamp($__unixEpochTo())) - EXTRACT(EPOCH FROM to_timestamp($__unixEpochFrom()))) * EXTRACT(EPOCH FROM (to_timestamp($__unixEpochTo()) - GREATEST(n.iflostservice, to_timestamp($__unixEpochFrom())))) AS availability,\n  to_timestamp($__unixEpochTo()) - n.iflostservice AS duration_raw,\n  EXTRACT(DAYS FROM to_timestamp($__unixEpochTo()) - n.iflostservice) || 'd ' || EXTRACT(HOURS FROM to_timestamp($__unixEpochTo()) - n.iflostservice) || 'h ' || EXTRACT(MINUTES FROM to_timestamp($__unixEpochTo()) - n.iflostservice) || 'm ' || ROUND(EXTRACT(SECONDS FROM to_timestamp($__unixEpochTo()) - n.iflostservice)::NUMERIC,0) || 's' AS duration\nFROM\n  node_outages n\nJOIN\n  node_outage_status nos\nON\n  n.nodeid = nos.nodeid\nWHERE\n  n.resolved = FALSE AND\n  n.svclosteventuei = 'uei.opennms.org/nodes/nodeLostService' AND\n  nos.max_outage_severity = '5' AND\n  n.categoryname IN ($category) AND\n  n.location IN ($location)\nGROUP BY\n  n.location,\n  n.nodelabel,\n  n.iflostservice,\n  n.ipaddr,\n  n.eventseverity,\n  n.servicename\nORDER BY\n  duration_raw DESC,\n  availability ASC,\n  n.location ASC,\n  n.nodelabel ASC,\n  n.ipaddr ASC,\n  n.servicename ASC"
    }
   ]
  }
 ]
}