{
 "title": "Earnings Test",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "miner",
    "query": {
     "query": "label_values(exported_instance)"
    }
   },
   { "name": "currency", "query": { "query": "label_values(currency)" } },
   { "name": "wallet", "query": { "query": "label_values(wallet)" } }
  ]
 },
 "panels": [
  { "title": "Market", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Real Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Reward Scale",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hnt_miner_reward_scale{exported_instance!=\"\",exported_instance=~\"$miner\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "HNT Earned 15m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 5, "y": 2 },
   "targets": [
    {
     "expr": "hnt_miner_reward_earned_15m{exported_instance!=\"\",exported_instance=~\"$miner\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "avg(hnt_miner_reward_earned_15m{exported_instance!=\"\",exported_instance=~\"$miner\"}) != 0",
     "legendFormat": "Avg"
    },
    {
     "expr": "sum(hnt_miner_reward_earned_15m{exported_instance!=\"\",exported_instance=~\"$miner\"} and on (instance,job) push_time_seconds >= time()-(${__interval_ms}/1000))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Wallet",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hnt_miner_wallet_balance{wallet=~\"$wallet\"})",
     "legendFormat": "HNT"
    },
    {
     "expr": "sum(hnt_miner_wallet_balance{exported_instance!=\"\",wallet=~\"$wallet\"}) * ignoring(exported_instance,wallet) sum(hnt_miner_helium_oracle_price_current{exported_instance!=\"\",currency=~\"$currency\"})",
     "legendFormat": "${currency}"
    }
   ]
  },
  {
   "title": "Reward Activity",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "docId : *events AND type : \"Reward Received\" AND hotspot : \"${miner}\" ",
     "timeField": "collectionTime"
    }
   ]
  }
 ]
}