{
 "title": "Prometheus Singlestat label value",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Value to text",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "2061" }
   ]
  },
  {
   "title": "Prometheus version",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "prometheus_build_info" }
   ]
  },
  {
   "title": "value range to text",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(go_goroutines)" }
   ]
  }
 ]
}