{
 "title": "Community Engineering Scorecard",
 "time": { "from": "2022-11-01T10:00:00.000Z", "to": "2023-02-01T09:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "category",
    "label": "Category",
    "query": "installation : 18, alerting : 60, piechart : 50, timeseries : 24, no subcategory : 33, loki : 41, grafana cloud : 34, tempo : 40, plugin development : 30, documentation : 39, lounge : 42, configuration : 20, azure monitor : 43, graphite : 13, elasticsearch : 14, authentication : 22, time series : 24, table : 26, stat : 25, prometheus : 15, influxDB : 11, development/api : 44, plugins - publishing : 45, plugins - showcase : 46, plugins - announcements : 47, gauge : 51, bar chart : 52, bar gauge : 53, mysql : 54, postgres : 55, cloudwatch : 56, graph (old) : 57, zabbix : 58, mssql : 59, dashboards : 61, explore : 62, live : 63, geomap : 64, data-links : 65"
   },
   {
    "name": "start",
    "label": "Start Date",
    "query": "start of 2022q1 : 2022-02-01, start of 2022q2 : 2022-05-01, start of 2022q3 : 2022-08-01, start of 2022q4 : 2022-11-01, start of 2023q1 : 2023-02-01, start of 2023q2 : 2023-05-01, start of 2023q3 : 2023-08-01, start of 2023q4 : 2023-11-01"
   },
   {
    "name": "end",
    "label": "End Date",
    "query": "end of 2022q1 : 2022-05-01, end of 2022q2 : 2022-08-01, end of 2022q3 : 2022-11-01, end of 2022q4 : 2023-02-01, end of 2023q1 : 2023-05-01, end of 2023q2 : 2023-08-01, end of 2023q3 : 2023-11-01, end of 2023q4 : 2024-02-01"
   }
  ]
 },
 "panels": [
  { "title": "Panel test", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  { "title": "Community Forum Response Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Response Rate per Category: from ${start} to ${end}",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groq": "*",
     "parser": "backend",
     "root_selector": "rows",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://community.grafana.com/admin/plugins/explorer/queries/28/run?params=%7B%22date_from%22%3A%22${start}%22%2C%22date_to%22%3A%22${end}%22%2C%22cat%22%3A%22${category}%22%7D",
     "url_options": { "body_content_type": "application/json", "body_type": "none", "data": "", "method": "POST" }
    },
    {
     "groq": "*",
     "parser": "backend",
     "root_selector": "rows",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://community.grafana.com/admin/plugins/explorer/queries/29/run?params=%7B%22date_from%22%3A%22${start}%22%2C%22date_to%22%3A%22${end}%22%2C%22cat%22%3A%22${category}%22%7D",
     "url_options": { "body_content_type": "application/json", "body_type": "none", "data": "", "method": "POST" }
    }
   ]
  },
  {
   "title": "\"${category}\" category: topics with no response: 22Q4",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 6, "y": 9 },
   "targets": [
    {
     "groq": "*",
     "parser": "simple",
     "root_selector": "rows",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://community.grafana.com/admin/plugins/explorer/queries/14/run?params=%7B%22date_from%22%3A%22${start}%22%2C%22date_to%22%3A%22${end}%22%2C%22cat%22%3A%22${category}%22%7D",
     "url_options": {
      "body_content_type": "application/json",
      "body_form": [],
      "body_type": "x-www-form-urlencoded",
      "data": "",
      "headers": [
       { "key": "x-discourse-route", "value": "query/run" }
      ],
      "method": "POST",
      "params": []
     }
    }
   ]
  },
  {
   "title": "Response Rate: ALL categories",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "category": "33",
     "period": "monthly",
     "reportName": "topics_with_no_response.json",
     "searchArea": "topics_posts",
     "searchSort": "latest",
     "userQuery": "topPublicUsers"
    },
    {
     "category": "33",
     "period": "monthly",
     "reportName": "topics.json",
     "searchArea": "topics_posts",
     "searchSort": "latest",
     "userQuery": "topPublicUsers"
    }
   ]
  },
  {
   "title": "Replies Needed to Reach a Response Rate of:",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "% top 20 posts w/solution",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "spreadsheet": "1W33YtV9zm5Qa6Q79TZXZq-RXLze1FFusyaRr9_6Z2Hw"
    }
   ]
  },
  {
   "title": "Top 20 Posts Q4 2022",
   "type": "table",
   "description": "This Panel list the Top 20 posts based on the highest no. of views from the previous quarter.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "data": "id,title,reply_count,views,last_posted_at,category_id\n75330,\"Grafana OSS Debian repo changes Origin, Label; is this intended?\",0,3744,2022-11-20 19:30:03 UTC,18\n79788,Problem with debian repository key,3,1228,2023-01-28 19:01:05 UTC,18\n76083,Documentation of Alert Templating in Serious Need of Improvement!,46,1186,2023-01-31 08:16:54 UTC,60\n77602,Db query error: failed to connect to server - please inspect Grafana server log for details MYSQL,4,1102,2022-12-08 21:47:53 UTC,54\n78202,Reverse proxy - delayed connect error: 111,0,852,2022-12-19 15:31:59 UTC,20\n76895,How do I reset admin password,0,844,2022-12-06 07:33:21 UTC,18\n76126,Grafana - keycloak openid connect integration,0,744,2022-11-16 13:12:33 UTC,22\n75238,Loki and Promtail working but can't connect from Grafana,2,730,2022-11-05 19:31:57 UTC,41\n75718,\"Connection to Keycloak broken, possibly due to a Grafana upgrade\",5,689,2022-11-10 20:10:50 UTC,20\n75278,Dynamic Thresholds using variables in Grafana,1,634,2022-12-09 12:09:37 UTC,61\n77071,Unable to upgrade from 9.2.4 to 9.3.0 Debian,11,613,2022-12-06 10:56:21 UTC,18\n76603,login.OAuthLogin (NewTransportWithCode) after OAuth login,2,611,2022-11-23 07:50:17 UTC,22\n75423,Grafana max number of data points for display,0,570,2023-01-18 11:42:02 UTC,61\n75967,Problem error bad request 400,3,552,2022-12-14 13:26:24 UTC,20\n76761,Speed up long running Flux Query,3,546,2022-12-11 11:01:26 UTC,11\n76160,Azure OAuth2 - AADSTS900971: No reply address provided,0,545,2022-11-16 17:32:50 UTC,22\n76104,404 trying to install from debian repo,5,537,2022-11-17 12:28:40 UTC,18\n77190,Limit of 50 at SQL,5,533,2022-12-27 22:29:17 UTC,61\n78000,\"Lots of \"\"context canceled\"\" errors when running queries\",0,492,2023-01-27 13:17:25 UTC,41\n77291,Error 500 when update dashboard,0,488,2023-01-17 11:20:41 UTC,58\n",
     "parser": "backend",
     "source": "inline",
     "type": "csv",
     "uql": "parse-csv",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Repo Stats: grafana/grafana ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "\"unlabeled\" issues for triage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.unlabeled.gauge, '7d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "\"needs more info\" issues",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.needs_more_info.gauge, '1d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "\"needs investigation\" + \"triage/needs-confirmation\" issues",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.needs_investigation.gauge, '1d', 'avg', false), 2)"
    },
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.triage_needs_confirmation.gauge, '1d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "TOTAL open issues",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "diffSeries(#A, #B)",
     "targetFull": "diffSeries(summarize(gh_action.repo.open_issues_count, '1d', 'avg', false), summarize(gh_action.issue_query.open_prs.gauge, '1d', 'avg', false))"
    }
   ]
  },
  {
   "title": "\"unlabeled\" issues for triage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.unlabeled.gauge, '1d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "\"needs more info\" issues",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.needs_more_info.gauge, '1d', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "\"triage/needs-confirmation\" + \"needs investigation\" issues",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 34 }
   ]
  },
  {
   "title": "TOTAL open issues",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "diffSeries(#A, #B)",
     "targetFull": "diffSeries(summarize(gh_action.repo.open_issues_count, '1d', 'avg', false), summarize(gh_action.issue_query.open_prs.gauge, '1d', 'avg', false))"
    }
   ]
  },
  {
   "title": "issues with no assigned project",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "options": {
      "query": "label:\"needs investigation\" no:project is:open"
     },
     "owner": "grafana",
     "repository": "grafana"
    },
    {
     "options": {
      "query": "label:\"triage/needs-confirmation\" no:project is:open"
     },
     "owner": "grafana",
     "repository": "grafana"
    }
   ]
  }
 ]
}