{
 "title": "Flowcharting - Grafana Play Home",
 "tags": [ "flowcharting" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Grafana diagram architecture",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(movingAverage(scaleToSeconds(apps.fakesite.*.counters.requests.count, 1), 2), 2)"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_95,1),'cpu1')"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_75,-1),'cpu2')"
    }
   ]
  },
  {
   "title": "server requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(movingAverage(scaleToSeconds(apps.fakesite.*.counters.requests.count, 1), 2), 2)"
    }
   ]
  },
  {
   "title": "client side full page load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(statsd.fakesite.timers.ads_timer.*, '4min', 'avg'), 4)"
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.request_status.code_302.count, 10), 20), 'cpu')"
    },
    {
     "target": "alias(statsd.fakesite.counters.session_start.desktop.count, 'memory')"
    }
   ]
  },
  {
   "title": "Traffic In/Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(statsd.fakesite.timers.ads_timer.*,4)"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_95,-1),'cpu1')"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_75,-1),'cpu2')"
    }
   ]
  },
  {
   "title": "logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), 2), 'logins')"
    },
    {
     "target": "alias(movingAverage(timeShift(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), '1h'), 2), 'logins (-1 hour)')"
    }
   ]
  }
 ]
}