{
 "title": "State Duration Data",
 "description": "used for InfluxDB alerting",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Tank",
    "label": "Tank ID",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: \"HyperEncabulator\",\r\n    tag: \"Tank\"\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"RetroEncabulator\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BooleanData\")\n  |> filter(fn: (r) => r[\"Location\"] == \"FrontDoor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"switch_state\")\n  |> yield(name: \"switch_state\")"
    }
   ]
  },
  {
   "title": "State over past 15 minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"RetroEncabulator\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BooleanData\")\n  |> filter(fn: (r) => r[\"Location\"] == \"FrontDoor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"switch_state\")\n  |> stateDuration(fn: (r) => r._value == true)\n  |> group(columns: [\"_value\"])\n  |> count(column: \"stateDuration\")\n  |> yield(name: \"switch_state\")"
    }
   ]
  },
  {
   "title": "State over past 24 hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"RetroEncabulator\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BooleanData\")\n  |> filter(fn: (r) => r[\"Location\"] == \"FrontDoor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"switch_state\")\n  |> stateDuration(fn: (r) => r._value == true)\n  |> group(columns: [\"_value\"])\n |> count(column: \"stateDuration\")\n  |> yield(name: \"switch_state\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 17, "w": 14, "x": 10, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"RetroEncabulator\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BooleanData\")\n  |> filter(fn: (r) => r[\"Location\"] == \"FrontDoor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"switch_state\")\n  |> yield(name: \"switch_state\")"
    }
   ]
  },
  {
   "title": "Sample Data",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 17, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"HyperEncabulator\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureData\")\r\n  |> filter(fn: (r) => r[\"MeasType\"] == \"actual\")\r\n  |> filter(fn: (r) => r[\"Tank\"] == \"B4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"HyperEncabulator\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureData\")\r\n  |> filter(fn: (r) => r[\"MeasType\"] == \"actual\")\r\n  |> filter(fn: (r) => r[\"Tank\"] == \"C3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "The current time is",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 45 },
   "targets": [
    {
     "query": "import \"array\"\nimport \"system\"\n\narray.from(rows: [{time: system.time()}])"
    }
   ]
  },
  {
   "title": "Temperature Data",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "query": "from(bucket: \"HyperEncabulator\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureData\")\r\n  |> filter(fn: (r) => r[\"MeasType\"] == \"setpoint\" or r[\"MeasType\"] == \"actual\")\r\n  |> filter(fn: (r) => r[\"Tank\"] == \"${Tank}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}