{
 "title": "Gapminder-ish (Hans Rosling)",
 "time": { "from": "now-20y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country_name",
    "label": "Country Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>World Country Data</h1>\n\n  <h3>Population vs. Avg. Life Expectancy</h3>\n  <ul> \n    <li>Based on BigQuery Public data</li>\n    <li>Select Country Details</li>\n  </ul>\n           "
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<div>\n  <img src=\"https://grafana.com/static/assets/internal/grafana_logo-web.svg\">\n</div>"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<div style=\"vertical-align: top; border: 0px;\"\">\n    <p style=\"text-align: center; font-size: 150%; padding: 0px; margin: 0px;\">\n        <b>Country Population and Life Expectancy</b>\n    </p>\n    <p style=\"text-align: center; font-size: 95%; padding: 0px; margin: 0px\">\n        <em>(select country via count_name variable or by clicking on a bubble in the bubble chart)</em>\n    </p> \n</div>"
   }
  },
  {
   "title": "${country_name} Detail Stats",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 16 }
   ]
  },
  {
   "title": "Country Population Growth vs. Life Expectancy",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 7 },
   "targets": [
    {
     "location": "US",
     "project": "chris-analytics-testing",
     "rawSql": "-- Panel: selected country details\nwith\n\npopulation_data as (\n\n    select\n        parse_date('%Y', cast(p.year as string)) as year\n        ,p.country_name\n        ,p.midyear_population as current_year_population\n        ,lag(p.midyear_population) over (partition by p.country_name order by year asc) as last_year_population\n    from\n        bigquery-public-data.census_bureau_international.midyear_population p\n    where\n        parse_date('%Y', cast(p.year as string)) <= date_trunc(current_date, year)\n\n),\n\nlife_expectancy_data as (\n\n    select\n        parse_date('%Y', cast(e.year as string)) as year\n        ,e.country_name\n        ,e.life_expectancy\n    from\n        bigquery-public-data.census_bureau_international.mortality_life_expectancy e\n\n),\n\nfinal as (\n\n    select\n        cast(p.year as timestamp) as year\n        ,p.country_name\n        ,p.current_year_population\n        ,p.last_year_population\n        ,(1.0 * p.current_year_population / p.last_year_population) - 1 as population_growth_rate\n        ,e.life_expectancy as average_life_expectancy\n        ,case when p.country_name = '${country_name}' then 1 else 0 end as is_selected\n    from\n        population_data p\n        left join life_expectancy_data e\n            on p.country_name = e.country_name\n            and p.year = e.year\n    where\n        $__timeFilter(cast(p.year as timestamp))\n    qualify max(p.year) over (partition by 1) = p.year\n    order by 1\n)\n\nselect *\nfrom final\norder by is_selected\n"
    }
   ]
  },
  {
   "title": "Population by Age Group",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "location": "US",
     "project": "chris-analytics-testing",
     "rawSql": "-- Panel: selected country population current year histogram\n\n-- notes:\n-- - check data in total_flag column?\n\nwith\n\npopulation_5yr_data as (\n\n    select\n        parse_date('%Y', cast(p.year as string)) as year\n        ,p.starting_age\n        ,p.midyear_population as total_population\n    from\n        bigquery-public-data.census_bureau_international.midyear_population_5yr_age_sex p\n    where\n        p.country_name = '${country_name}'\n        and p.total_flag = 'A'\n    order by 1\n\n),\n\nhistogram_data as (\n\n    select\n        p.year\n        ,p.starting_age\n        ,p.total_population\n    from\n        population_5yr_data p\n    where\n        $__timeFilter(cast(p.year as timestamp))\n        and p.year <= '2022-01-01'\n\n),\n\nfinal as (\n\n    -- also not sure that this works...\n    select *\n    from histogram_data\n    qualify year = max(year) over (partition by 1)\n\n)\n\nselect *\nfrom final\norder by 2\n"
    }
   ]
  },
  {
   "title": "Country Population by Year",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "location": "US",
     "project": "chris-analytics-testing",
     "rawSql": "-- Panel: selected country population by year\n\nwith \n\npopulation_data as (\n\n    select\n        parse_date('%Y', cast(p.year as string)) as year\n        ,p.country_name\n        ,p.midyear_population as current_year_population\n        ,lag(p.midyear_population) over (partition by p.country_name order by year asc) as last_year_population\n    from\n        bigquery-public-data.census_bureau_international.midyear_population p\n    where\n        parse_date('%Y', cast(p.year as string)) <= date_trunc(current_date, year)\n\n)\n\nselect\n    cast(p.year as timestamp) as year\n    ,p.current_year_population as total_population\nfrom\n    population_data p\nwhere\n    $__timeFilter(cast(p.year as timestamp))\n    and p.country_name = '${country_name}'\n    and p.year <= '2022-01-01'\norder by 1\n"
    }
   ]
  },
  { "title": "Appendix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Other Business Intelligence Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "[Temp (new XY Chart)] Country Population Growth vs. Life Expectancy",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 38 },
   "targets": [
    {
     "location": "US",
     "project": "chris-analytics-testing",
     "rawSql": "-- Panel: selected country details\nwith\n\npopulation_data as (\n\n    select\n        parse_date('%Y', cast(p.year as string)) as year\n        ,p.country_name\n        ,p.midyear_population as current_year_population\n        ,lag(p.midyear_population) over (partition by p.country_name order by year asc) as last_year_population\n    from\n        bigquery-public-data.census_bureau_international.midyear_population p\n    where\n        parse_date('%Y', cast(p.year as string)) <= date_trunc(current_date, year)\n\n),\n\nlife_expectancy_data as (\n\n    select\n        parse_date('%Y', cast(e.year as string)) as year\n        ,e.country_name\n        ,e.life_expectancy\n    from\n        bigquery-public-data.census_bureau_international.mortality_life_expectancy e\n\n),\n\nfinal as (\n\n    select\n        cast(p.year as timestamp) as year\n        ,p.country_name\n        ,p.current_year_population\n        ,p.last_year_population\n        ,(1.0 * p.current_year_population / p.last_year_population) - 1 as population_growth_rate\n        ,e.life_expectancy as average_life_expectancy\n        ,case when p.country_name = '${country_name}' then 'rgb(222, 182, 242)' else 'rgb(204, 204, 220)' end as color\n    from\n        population_data p\n        left join life_expectancy_data e\n            on p.country_name = e.country_name\n            and p.year = e.year\n    where\n        $__timeFilter(cast(p.year as timestamp))\n    qualify max(p.year) over (partition by 1) = p.year\n    order by 1\n)\n\nselect *\nfrom final\norder by color\n"
    }
   ]
  }
 ]
}