{
 "title": "#46510 Lots of variable freeze",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Search", "query": { "query": "label_names()" } },
   { "name": "SearchResults", "query": { "query": "label_values($Search)" } },
   {
    "name": "Handler",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, handler)"
    }
   },
   {
    "name": "Auto_address",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, address)"
    }
   },
   {
    "name": "Auto_alertmanager",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, alertmanager)"
    }
   },
   {
    "name": "Auto_alertname",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, alertname)"
    }
   },
   {
    "name": "Auto_alertstate",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, alertstate)"
    }
   },
   {
    "name": "Auto_branch",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, branch)"
    }
   },
   {
    "name": "Auto_broadcast",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, broadcast)"
    }
   },
   {
    "name": "Auto_call",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, call)"
    }
   },
   {
    "name": "Auto_cause",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, cause)"
    }
   },
   {
    "name": "Auto_code",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, code)"
    }
   },
   {
    "name": "Auto_collector",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, collector)"
    }
   },
   {
    "name": "Auto_config",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, config)"
    }
   },
   {
    "name": "Auto_cpu",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, cpu)"
    }
   },
   {
    "name": "Auto_device",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, device)"
    }
   },
   {
    "name": "Auto_dialer_name",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, dialer_name)"
    }
   },
   {
    "name": "Auto_domainname",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, domainname)"
    }
   },
   {
    "name": "Auto_duplex",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, duplex)"
    }
   },
   {
    "name": "Auto_endpoint",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, endpoint)"
    }
   },
   {
    "name": "Auto_event",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, event)"
    }
   },
   {
    "name": "Auto_fstype",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, fstype)"
    }
   },
   {
    "name": "Auto_goversion",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, goversion)"
    }
   },
   {
    "name": "Auto_handler",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, handler)"
    }
   },
   {
    "name": "Auto_instance",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, instance)"
    }
   },
   {
    "name": "Auto_integration",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, integration)"
    }
   },
   {
    "name": "Auto_interval",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, interval)"
    }
   },
   {
    "name": "Auto_ip",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, ip)"
    }
   },
   {
    "name": "Auto_job",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, job)"
    }
   },
   {
    "name": "Auto_key",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, key)"
    }
   },
   {
    "name": "Auto_le",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, le)"
    }
   },
   {
    "name": "Auto_listener_name",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, listener_name)"
    }
   },
   {
    "name": "Auto_machine",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, machine)"
    }
   },
   {
    "name": "Auto_method",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, method)"
    }
   },
   {
    "name": "Auto_mode",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, mode)"
    }
   },
   {
    "name": "Auto_mountpoint",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, mountpoint)"
    }
   },
   {
    "name": "Auto_msg_type",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, msg_type)"
    }
   },
   {
    "name": "Auto_name",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, name)"
    }
   },
   {
    "name": "Auto_nodename",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, nodename)"
    }
   },
   {
    "name": "Auto_operstate",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, operstate)"
    }
   },
   {
    "name": "Auto_peer",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, peer)"
    }
   },
   {
    "name": "Auto_quantile",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, quantile)"
    }
   },
   {
    "name": "Auto_queue",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, queue)"
    }
   },
   {
    "name": "Auto_reason",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, reason)"
    }
   },
   {
    "name": "Auto_release",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, release)"
    }
   },
   {
    "name": "Auto_revision",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, revision)"
    }
   },
   {
    "name": "Auto_role",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, role)"
    }
   },
   {
    "name": "Auto_rule_group",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, rule_group)"
    }
   },
   {
    "name": "Auto_scrape_job",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, scrape_job)"
    }
   },
   {
    "name": "Auto_slice",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, slice)"
    }
   },
   {
    "name": "Auto_state",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, state)"
    }
   },
   {
    "name": "Auto_status",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, status)"
    }
   },
   {
    "name": "Auto_sysname",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, sysname)"
    }
   },
   {
    "name": "Auto_type",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, type)"
    }
   },
   {
    "name": "Auto_version",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, version)"
    }
   },
   {
    "name": "Auto_x",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, x)"
    }
   },
   {
    "name": "Auto_y",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\"}, y)"
    }
   },
   {
    "name": "Job",
    "query": {
     "query": "label_values({$Search=~\"$SearchResults\", handler=~\"$Handler\"}, job)"
    }
   },
   {
    "name": "Collector",
    "query": {
     "query": "label_values({job=~\"${Job}\"},  collector)"
    }
   },
   {
    "name": "query0",
    "query": "Auto_alertmanager,Auto_alertname,Auto_alertstate,Auto_branch,Auto_call,Auto_code,Auto_config,Auto_dialer_name,Auto_endpoint,Auto_event,Auto_goversion,Auto_handler,Auto_instance,Auto_interval,Auto_job,Auto_le,Auto_listener_name,Auto_name,Auto_quantile,Auto_reason,Auto_revision,Auto_role,Auto_rule_group,Auto_scrape_job,Auto_slice,Auto_version"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": " - Auto_alertmanager: $Auto_alertmanager\n - Auto_alertname: $Auto_alertname\n - Auto_alertstate: $Auto_alertstate\n - Auto_branch: $Auto_branch\n - Auto_call: $Auto_call\n - Auto_code: $Auto_code\n - Auto_config: $Auto_config\n - Auto_dialer_name: $Auto_dialer_name\n - Auto_endpoint: $Auto_endpoint\n - Auto_event: $Auto_event\n - Auto_goversion: $Auto_goversion\n - Auto_handler: $Auto_handler\n - Auto_instance: $Auto_instance\n - Auto_interval: $Auto_interval\n - Auto_job: $Auto_job\n - Auto_le: $Auto_le\n - Auto_listener_name: $Auto_listener_name\n - Auto_name: $Auto_name\n - Auto_quantile: $Auto_quantile\n - Auto_reason: $Auto_reason\n - Auto_revision: $Auto_revision\n - Auto_role: $Auto_role\n - Auto_rule_group: $Auto_rule_group\n - Auto_scrape_job: $Auto_scrape_job\n - Auto_slice: $Auto_slice\n - Auto_version: $Auto_version"
   }
  },
  { "title": "non-repeating", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "uses handler variable: $Handler",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{handler=~\"${Handler}\"}"
    }
   ]
  },
  {
   "title": "uses job variable: $Job",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "{job=~\"${Job}\"}"
    }
   ]
  },
  {
   "title": "uses SearchResults($SearchResults) and Handler($Handler)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "{instance=~\"${SearchResults}\", handler=~\"${Handler}\"}"
    }
   ]
  },
  {
   "title": "(repeat SearchResults) $SearchResults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "SearchResults"
  },
  {
   "title": "repeat Handler: $Handler",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "repeat": "Handler",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{instance=~\"${SearchResults}\", handler=~\"${Handler}\"}"
    }
   ]
  }
 ]
}