{
 "title": "Import test",
 "tags": [
  "startpage",
  "home",
  "Home"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Feature showcases", "type": "dashlist", "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 } },
  { "title": "Data source demos", "type": "dashlist", "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 } },
  { "title": "What's New", "type": "dashlist", "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "server requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(scaleToSeconds(apps.fakesite.*.counters.requests.count, 1), 2), 2)"
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.request_status.code_302.count, 10), 20), 'cpu')"
    },
    {
     "target": "alias(statsd.fakesite.counters.session_start.desktop.count, 'memory')"
    }
   ]
  },
  {
   "title": "client side full page load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(statsd.fakesite.timers.ads_timer.*, '4min', 'avg'), 4)"
    }
   ]
  },
  {
   "title": "logins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), 2), 'logins')"
    },
    {
     "target": "alias(movingAverage(timeShift(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), '1h'), 2), 'logins (-1 hour)')"
    }
   ]
  },
  {
   "title": "Traffic In/Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(statsd.fakesite.timers.ads_timer.*,4)"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_95,-1),'cpu1')"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_75,-1),'cpu2')"
    }
   ]
  }
 ]
}