{
 "title": "Graphite Templated Nested",
 "tags": [ "ds-example" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "query": "apps.*" },
   { "name": "server", "query": "apps.$app.*" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(movingAverage(apps.$app.$server.counters.requests.count, 10), 2, 'sum')"
    }
   ]
  },
  {
   "title": "Requests / $interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(summarize(movingAverage(apps.$app.$server.counters.requests.count, 5), '$interval', 'sum', false), 2, 'sum')"
    }
   ]
  },
  {
   "title": "$server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "repeat": "server",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(apps.$app.$server.counters.requests.count, 2)"
    }
   ]
  }
 ]
}