{
 "title": "Datasource tests - Elasticsearch v7",
 "tags": [
  "elasticsearch",
  "gdev",
  "datasource-test"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top 5 servers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@hostname",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Percentiles & Metric filter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "@metric:cpu",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Standard dev",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {
        "std_deviation_bounds_lower": true,
        "std_deviation_bounds_upper": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "@metric:cpu",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ES Metrics",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@hostname",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "@value",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "@value",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ES Log query",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "World map panel",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@location",
       "id": "3",
       "settings": { "precision": 2 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}