{
 "title": "Datasource tests - Elasticsearch comparison",
 "tags": [
  "elasticsearch",
  "gdev",
  "datasource-test"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "version_one", "label": "Version One", "query": "elasticsearch" },
   { "name": "version_two", "label": "Version Two", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Basic date histogram with count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Basic (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic (version one) - interval 1m + min doc count 50",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 50 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic (version two) - interval 1m + min doc count 50",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 50 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic (version one) - interval 5m + trim edges=10",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 10 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Basic (version two) - interval 5m + trim edges=10",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 10 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic date histogram with metric aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "avg (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "avg (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "sum (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "sum (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "max (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "max (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "min (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "min"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "min (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "min"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "extended stats (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": true,
          "count": true,
          "max": true,
          "min": true,
          "std_deviation": true,
          "std_deviation_bounds_lower": true,
          "std_deviation_bounds_upper": true,
          "sum": true
         },
         "settings": {},
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "extended stats (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": true,
          "count": true,
          "max": true,
          "min": true,
          "std_deviation": true,
          "std_deviation_bounds_lower": true,
          "std_deviation_bounds_upper": true,
          "sum": true
         },
         "settings": {},
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "percentiles (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {
          "percents": [
           25,
           50,
           75,
           95,
           99
          ]
         },
         "type": "percentiles"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "percentiles (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {
          "percents": [
           25,
           50,
           75,
           95,
           99
          ]
         },
         "type": "percentiles"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "unique count (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "unique count (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic date histogram with moving average aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "count (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "avg (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "avg (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "sum (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "sum (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "max (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "max (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "min (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "min"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "min (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "min"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "unique count (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "unique count (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {
          "minimize": false,
          "model": "simple",
          "window": 5
         },
         "type": "moving_avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic date histogram with derivative aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "count (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "avg (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "avg (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "sum (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "sum (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "max (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "max (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "min (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "min"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "min (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "min"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "unique count (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "unique count (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic date histogram with cumulative sum aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "count (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:344",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:340",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        },
        {
         "$$hashKey": "object:341",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:344",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:340",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        },
        {
         "$$hashKey": "object:341",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "avg (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:546",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:542",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:543",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "avg (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:546",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:542",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:543",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "sum (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:731",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:727",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "$$hashKey": "object:728",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "sum (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:731",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:727",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "$$hashKey": "object:728",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "max (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:885",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:881",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "$$hashKey": "object:882",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "max (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:885",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:881",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "$$hashKey": "object:882",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "min (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1039",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1035",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "min"
        },
        {
         "$$hashKey": "object:1036",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "min (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1039",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1035",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "min"
        },
        {
         "$$hashKey": "object:1036",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "unique count (version one) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1193",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1189",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        },
        {
         "$$hashKey": "object:1190",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "unique count (version two) - interval 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1193",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1189",
         "field": "@value",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "cardinality"
        },
        {
         "$$hashKey": "object:1190",
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "cumulative_sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic date histogram with bucket script aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "count * 1000 (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": true,
         "id": "1",
         "type": "count"
        },
        {
         "field": "select field",
         "id": "3",
         "meta": {},
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" }
         ],
         "settings": { "script": "params.var1 * 1000" },
         "type": "bucket_script"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count * 1000 (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": true,
         "id": "1",
         "type": "count"
        },
        {
         "field": "select field",
         "id": "3",
         "meta": {},
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" }
         ],
         "settings": { "script": "params.var1 * 1000" },
         "type": "bucket_script"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count * avg (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": true,
         "id": "1",
         "type": "count"
        },
        {
         "field": "@value",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "select field",
         "id": "4",
         "meta": {},
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" },
          { "name": "var2", "pipelineAgg": "3" }
         ],
         "settings": { "script": "params.var1 * params.var2" },
         "type": "bucket_script"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count * avg (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": true,
         "id": "1",
         "type": "count"
        },
        {
         "field": "@value",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "select field",
         "id": "4",
         "meta": {},
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "1" },
          { "name": "var2", "pipelineAgg": "3" }
         ],
         "settings": { "script": "params.var1 * params.var2" },
         "type": "bucket_script"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Multiple metrics and aggregations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "count/average with triple terms agg (version one) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{@source}} - {{@hostname}} - {{@metric}} {{metric}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "@source",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "@metric",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" },
        {
         "field": "@value",
         "id": "6",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "count/average with triple terms agg (version two) - interval auto",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{@source}} - {{@hostname}} - {{@metric}} {{metric}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "@source",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "@metric",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" },
        {
         "field": "@value",
         "id": "6",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Terms order by simple aggregation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terms order by Doc Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by Doc Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by Term value",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by Term value",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "@value", "id": "1", "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "@value", "id": "1", "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by unique count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "@value", "id": "1", "type": "cardinality" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by unique count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "@value", "id": "1", "type": "cardinality" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Terms order by extended stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terms order by extended stats (avg)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[avg]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": true,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (avg)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[avg]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": true,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (min)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[min]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": true,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (min)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[min]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": true,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (max)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[max]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": true,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (max)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[max]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": true,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (sum)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[sum]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": true
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (sum)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[sum]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": true
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (count)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[count]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": true,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (count)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[count]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": true,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (std dev)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[std_deviation]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (std dev)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[std_deviation]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (std dev upper)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[std_upper]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": true,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (std dev upper)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[std_upper]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": true,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (std dev lower)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[std_lower]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": true,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by extended stats (std dev lower)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[std_lower]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "@value",
         "id": "1",
         "meta": {
          "avg": false,
          "count": false,
          "max": false,
          "min": false,
          "std_deviation": false,
          "std_deviation_bounds_lower": true,
          "std_deviation_bounds_upper": false,
          "sum": false
         },
         "type": "extended_stats"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Terms order by percentile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terms order by percentile (25)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[25.0]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "@value", "id": "1", "settings": { "percents": [ "25" ] }, "type": "percentiles" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by percentile (25)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1[25.0]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "@value", "id": "1", "settings": { "percents": [ "25" ] }, "type": "percentiles" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by percentile (99)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[99.0]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "@value", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Terms order by percentile (99)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@hostname",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "1[99.0]", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "@value", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Inline scripts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Old & new script format",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "New Script Format",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "@value", "id": "1", "settings": { "script": "_value * 2" }, "type": "avg" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Old Script Format",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "@value", "id": "1", "settings": { "script": { "inline": "_value * 1.5" } }, "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Old & new script format",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "alias": "New Script Format",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "@value", "id": "1", "settings": { "script": "_value * 2" }, "type": "avg" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Old Script Format",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "@value", "id": "1", "settings": { "script": { "inline": "_value * 1.5" } }, "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}