{
 "title": "icon navbar bad",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Feature showcases",
   "type": "text",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Welcome to Grafana nav poc\n\nWelcome to a design exploration proof-of-concept and experiment. \n\n## Disclaimers\n \n* This is just a design poc. Super quick and dirty poc to get a feel for this design option. If we want to build this for real there would be little that could be re-used (code wise). \n* It is not a complete poc. Many sections are not working properly. \n\n## Working sections with proper sub nav (item level nav)\n\n* Dashbord\n* Dashboard settings \n* Dashboard settings / annotations \n* Dashboard / view panel and edit panel\n* Administration / Data sources\n* Administration / Teams \n\n## Not working / updated\n* Dashboard folders have not been updated to support this new sub nav\n* Other sections will not have proper sub nav when going into items (page and breadcrumb will look off)\n* Profile drawer is just super duper quick version of an awesome design made by Luke. I only did enough to get the idea / feel across, but is just 20% of that design.  \n* No search poc implemented. Imagine search bar expands when given focus and a popover dropdown shows up quickly that allow you to search across everything in Grafana (incl pages and sections.)\n\n## Refinements missing\n\n* Being able to collapse second level section side-nav\n* Being able to collapse the top bar (See google docs for good reference)\n\n## Problem definitions \n\n[Dashboard detailing the problems this nav is trying to solve](http://grafana-poc.codinginstinct.com:3000/d/I7uyW-w7k/problem-definition?orgId=1)\n\n"
   }
  },
  { "title": "Data source demos", "type": "dashlist", "gridPos": { "h": 11, "w": 8, "x": 0, "y": 21 } },
  { "title": "What's New", "type": "dashlist", "gridPos": { "h": 11, "w": 16, "x": 8, "y": 21 } },
  {
   "title": "server requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(scaleToSeconds(apps.fakesite.*.counters.requests.count, 1), 2), 2)"
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.request_status.code_302.count, 10), 20), 'cpu')"
    },
    {
     "target": "alias(statsd.fakesite.counters.session_start.desktop.count, 'memory')"
    }
   ]
  },
  {
   "title": "client side full page load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(statsd.fakesite.timers.ads_timer.*, '4min', 'avg'), 4)"
    }
   ]
  },
  {
   "title": "logins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), 2), 'logins')"
    },
    {
     "target": "alias(movingAverage(timeShift(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), '1h'), 2), 'logins (-1 hour)')"
    }
   ]
  },
  {
   "title": "Traffic In/Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(statsd.fakesite.timers.ads_timer.*,4)"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_95,-1),'cpu1')"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_75,-1),'cpu2')"
    }
   ]
  }
 ]
}