{
 "title": "grafana/grafana stats",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "grafana/grafana PRs: Community vs Grafanistas",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  proposed_by AS metric,\n  opened\nFROM pr_activity\nWHERE\n  $__unixEpochFilter(time) AND repo=\"grafana/grafana\"\nORDER BY time"
    }
   ]
  },
  {
   "title": "grafana/grafana median age of PRs: community vs. grafanista",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  proposed_by AS metric,\n  median_age\nFROM pr_age\nWHERE\n  $__unixEpochFilter(time) and repo=\"grafana/grafana\"\nORDER BY time"
    }
   ]
  },
  {
   "title": "grafana/grafana issue_comments_activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  authored_by AS metric,\n  count\nFROM issue_comments_activity\nWHERE\n  $__unixEpochFilter(time) AND repo=\"grafana/grafana\"\nORDER BY time"
    }
   ]
  },
  {
   "title": "grafana/grafana issue_comments_activity EVENTS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  event_type AS metric,\n  count\nFROM events_activity\nWHERE\n  $__unixEpochFilter(time) AND repo=\"grafana/grafana\"\nORDER BY time"
    }
   ]
  }
 ]
}