{
 "title": "Grafana Play Home in an alternate universe",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background:url('/public/img/login_background_dark.svg');padding:20px\">\n<h1>Just getting started?</h1>\n<h4>Nice to meet you! Take a quick tour of Grafana through the eyes of Pelican, a possibly-fictional company that uses Grafana's tools to manage its grocery delivery business.</h4>\n<br/>\n<a href=\"https://dev.se-demo.grafana.net/d/HsviN-z7z/0-pelican-introduction?orgId=1\">\n    <div class=\"btn btn-primary\">Take a spin around Grafana</div>\n  </a>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Feature showcases", "type": "dashlist", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 } },
  { "title": "Data source demos", "type": "dashlist", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 } },
  { "title": "What's New", "type": "dashlist", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 } },
  {
   "title": "server requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(scaleToSeconds(apps.fakesite.*.counters.requests.count, 1), 2), 2)"
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.request_status.code_302.count, 10), 20), 'cpu')"
    },
    {
     "target": "alias(statsd.fakesite.counters.session_start.desktop.count, 'memory')"
    }
   ]
  },
  {
   "title": "client side full page load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(statsd.fakesite.timers.ads_timer.*, '4min', 'avg'), 4)"
    }
   ]
  },
  {
   "title": "logins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), 2), 'logins')"
    },
    {
     "target": "alias(movingAverage(timeShift(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), '1h'), 2), 'logins (-1 hour)')"
    }
   ]
  },
  {
   "title": "Traffic In/Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(statsd.fakesite.timers.ads_timer.*,4)"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_95,-1),'cpu1')"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_75,-1),'cpu2')"
    }
   ]
  }
 ]
}