{
 "title": "(Home) Kubernetes Integration",
 "tags": [
  "kubernetes-integration",
  "Start Here"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(kubelet_runtime_operations_total{cluster=\"$cluster\", job=\"integrations/kubernetes/kubelet\"}, instance)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"integrations/kubernetes/kubelet\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"padding: 10px;\">   <div style=\"margin-bottom: 30px;display: flex; flex-direction: row; align-items: center; margin-top: 10px;\">     <img style=\"height: 40px; width: 40px; margin-right: 10px;\" src=\"https://storage.googleapis.com/grafanalabs-integration-logos/kubernetes.svg\" />     <h2 style=\"margin-top: 5px;\">Welcome to Grafana Cloud for Kubernetes</h2>   </div>   <div style=\"display: flex; width: 100%;\">     <div style=\"width: 50%;\">       <div style=\"margin: 0 0 10px 0;display: flex; \">         <img style=\"margin-right: 20px; margin-top: 10px; height: 25px;\" src=\"https://storage.googleapis.com/k8s-integration-icons/compass.png\" alt=\"\">         <p style=\"width: 80%; margin-top: 5px;\">Visualize and query cAdvisor, Kubelet and kube-state-metrics for your K8s cluster(s)</p>       </div>       <div style=\"margin: 10px 0 10px 0;display: flex; \">         <img style=\"margin-right: 20px; margin-top: 10px; height: 25px;\" src=\"https://storage.googleapis.com/k8s-integration-icons/dash.png\" alt=\"\">         <p style=\"width: 80%; margin-top: 5px;\">Access premade dashboards for visibility into resource consumption and cluster operations</p>       </div>     </div>     <div style=\"width: 50%; margin-top: 0;\">       <div style=\"margin: 0 0 10px 0; display: flex; \">         <img style=\"margin-right: 20px; margin-top: 10px; height: 25px;\" src=\"https://storage.googleapis.com/k8s-integration-icons/bell.png\" alt=\"\">         <p style=\"width: 80%; margin-top: 5px;\">Create alerts based on cAdvisor and kube-state-metrics in Grafana Cloud Alerting</p>       </div>       <div style=\"margin: 0 0 10px 0; display: flex; \">         <img style=\"margin-right: 20px; margin-top: 10px; height: 25px;\" src=\"https://storage.googleapis.com/k8s-integration-icons/loki.svg\" alt=\"\">         <p style=\"width: 80%; margin-top: 5px;\">Collect and ship Pod logs to Grafana Cloud. Learn more <a href=\"https://grafana.com/docs/grafana-cloud/quickstart/agent-k8s/k8s_agent_logs/\" target=\"_blank\">here</a>.</p>       </div>     </div>   </div> </div>"
   }
  },
  {
   "title": "Configuration status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({job=\"integrations/kubernetes/kubelet\"})",
     "legendFormat": "Kubelet"
    },
    {
     "expr": "count({job=\"integrations/kubernetes/kube-state-metrics\"})",
     "legendFormat": "Kube State Metrics"
    },
    {
     "expr": "count({job=\"integrations/kubernetes/cadvisor\"})",
     "legendFormat": "cAdvisor"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "options": {
    "content": "<h3>Resource consumption visibility</h3> <p>We provide 7 pre-built dashboards that give you visibility into resource consumption, with drilldowns by cluster, Namespace, Pod, Node and more.</p>"
   }
  },
  {
   "title": "Cluster CPU usage (by Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Resource consumption visibility",
   "type": "dashlist",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "options": {
    "content": "<h3>Cluster operations visibility</h3> <p>We provide 2 pre-built dashboards that give you visibility into the operations of your K8s clusters, including Kubelet metrics and Persistent Volumes.</p> <a href=\"https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/\" target=\"_blank\">Read more about Kubelet ></a>"
   }
  },
  {
   "title": "Running pods",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{cluster=\"$cluster\", job=\"integrations/kubernetes/kubelet\", instance=~\"$instance\"}) OR sum(kubelet_running_pod_count{cluster=\"$cluster\", job=\"integrations/kubernetes/kubelet\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{cluster=\"$cluster\", job=\"integrations/kubernetes/kubelet\", instance=~\"$instance\"}) OR sum(kubelet_running_container_count{cluster=\"$cluster\", job=\"integrations/kubernetes/kubelet\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Cluster operations visibility", "type": "dashlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 } }
 ]
}