{
 "title": "Datasource tests - Loki",
 "tags": [
  "gdev",
  "loki",
  "datasource-test"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "place",
    "label": "Place",
    "query": {}
   },
   { "name": "adhoc", "label": "Ad-hoc" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "(Variable) $place logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{place=\"$place\"} |= ``",
     "maxLines": 60
    }
   ]
  },
  {
   "title": "(Variable) $place errors",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{place=\"$place\"} |= `error`",
     "maxLines": 60
    }
   ]
  },
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "(Variable) No. of $place logs over the last 5m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count_over_time({place=\"$place\"} [5m])",
     "legendFormat": "{{place}}",
     "maxLines": 60
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Moon Log count over 5m",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({place=\"moon\"} [5m])",
     "legendFormat": "{{place}}"
    }
   ]
  },
  {
   "title": "Luna Log count over 5m",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({place=\"luna\"} [5m])",
     "legendFormat": "{{place}}"
    }
   ]
  }
 ]
}