{
 "title": "Caddy Overview",
 "tags": [ "caddy-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(caddy_http_requests_total{handler=\"reverse_proxy\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Requests by Response Code",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(caddy_http_request_duration_seconds_count{handler=\"reverse_proxy\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests In Flight",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(caddy_http_requests_in_flight{handler=\"reverse_proxy\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Requests by Response Code (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(caddy_http_request_duration_seconds_count{handler=\"reverse_proxy\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request Duration (percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"reverse_proxy\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"reverse_proxy\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"reverse_proxy\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"reverse_proxy\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"reverse_proxy\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request Duration (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{handler=\"reverse_proxy\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}