{
 "title": "Grafana Play Home-bug test",
 "tags": [
  "startpage",
  "home",
  "Home"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Fraction 1.5",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1.5" }
   ]
  },
  { "title": "What's New", "type": "dashlist", "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Fraction ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": ".5" }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.request_status.code_302.count, 10), 20), 'cpu')"
    },
    {
     "target": "alias(statsd.fakesite.counters.session_start.desktop.count, 'memory')"
    }
   ]
  },
  {
   "title": "Whole number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "logins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), 2), 'logins')"
    },
    {
     "target": "alias(movingAverage(timeShift(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), '1h'), 2), 'logins (-1 hour)')"
    }
   ]
  },
  { "title": "Feature showcases", "type": "dashlist", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 } },
  { "title": "Data source demos", "type": "dashlist", "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 } },
  {
   "title": "server requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(scaleToSeconds(apps.fakesite.*.counters.requests.count, 1), 2), 2)"
    }
   ]
  },
  {
   "title": "client side full page load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(statsd.fakesite.timers.ads_timer.*, '4min', 'avg'), 4)"
    }
   ]
  },
  {
   "title": "Traffic In/Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(statsd.fakesite.timers.ads_timer.*,4)"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_95,-1),'cpu1')"
    },
    {
     "target": "alias(scale(statsd.fakesite.timers.ads_timer.upper_75,-1),'cpu2')"
    }
   ]
  }
 ]
}