{
 "title": "Web App Correlation",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Webapp",
    "query": {
     "query": "{service=~ \"web_app_.+\"}"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "{kubernetes_namespace=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background: url('https://i.ibb.co/gmYD7BN/gearbg.jpg'); background-repeat: no-repeat; background-size: cover;\">\n   <img src=\"https://i.ibb.co/QJyKvjZ/1397119524.png\" style=\"width:100px\" />\n   <span style=\"font-size: 2.5em; color: black; -webkit-text-stroke: 2px black\">WidgetCo Industries - Web App Overview</span>\n</div>\n"
   },
   "targets": [
    {
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Concurrent webapp users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "web_http_requests{service=~\"[[service]]\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(web_http_requests{service=~\"[[service]]\"})"
    }
   ]
  },
  {
   "title": "Error Rate (60s)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(web_http_5xx_errors[1m]) + rate(web_http_4xx_clients_errors[1m]) + rate(web_http_3xx_redirection[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Message Queue",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate({service=~\"[[service]]\"}[1s])) by (error_level)",
     "legendFormat": "{{error_level}}"
    }
   ]
  },
  {
   "title": "HTTP Server Logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({service=~\"[[service]]\"}[30s])) by (error_level)",
     "legendFormat": "{{error_level}}"
    }
   ]
  },
  {
   "title": "Percent of 500 HTTP Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(labels) (web_http_5xx_errors) / (sum by(labels) (web_http_5xx_errors) + sum by(labels) (web_http_3xx_redirection) + sum by(labels) (web_http_4xx_clients_errors) + sum by(labels) (web_http_2xx_success))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Stream",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{service=~\"[[service]]\"}"
    }
   ]
  }
 ]
}