{
 "title": "Cloudflare",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Cloudflare Log Pull API ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job) (count_over_time({job=\"cloudflare\"} | json [$__interval]))  "
    }
   ]
  },
  {
   "title": "Cache Response Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (CacheResponseStatus) (count_over_time({job=\"cloudflare\"} | json [$__interval])) ",
     "legendFormat": "Status {{CacheResponseStatus}}"
    }
   ]
  },
  {
   "title": "Cloudflare logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({job=\"cloudflare\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Total bytes served",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (sum_over_time({job=\"cloudflare\"} | json | unwrap CacheResponseBytes [$__interval]))"
    }
   ]
  },
  {
   "title": "# Cloudflare log lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"cloudflare\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Requests per Country",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (ClientCountry) (count_over_time({job=\"cloudflare\"} | json [$__interval]))",
     "legendFormat": "{{ClientCountry}}"
    }
   ]
  },
  {
   "title": "Client Device Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (ClientDeviceType) (count_over_time({job=\"cloudflare\"} | json [$__interval]))",
     "legendFormat": "{{ClientDeviceType}}"
    }
   ]
  },
  {
   "title": "Cache Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (CacheCacheStatus) (count_over_time({job=\"cloudflare\"} | json [$__interval]))",
     "legendFormat": "{{CacheCacheStatus}}"
    }
   ]
  },
  {
   "title": "Edge response content types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (EdgeResponseContentType) (count_over_time({job=\"cloudflare\"} | json [$__interval]))",
     "legendFormat": "{{EdgeResponseContentType}}"
    }
   ]
  },
  {
   "title": "Security Level requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (SecurityLevel) (count_over_time({job=\"cloudflare\"} | json [$__interval]))",
     "legendFormat": "{{SecurityLevel}}"
    }
   ]
  },
  {
   "title": "Caching status in bytes served",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (CacheCacheStatus) (sum_over_time({job=\"cloudflare\"} | json | unwrap CacheResponseBytes [$__interval]))",
     "legendFormat": "{{CacheCacheStatus}}"
    }
   ]
  },
  {
   "title": "Client IP class",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (ClientIPClass) (count_over_time({job=\"cloudflare\"} | json [$__interval]))",
     "legendFormat": "{{ClientIPClass}}"
    }
   ]
  },
  {
   "title": "Client SSL Protocol",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "sum by (ClientSSLProtocol) (count_over_time({job=\"cloudflare\"} | json [$__interval]))",
     "legendFormat": "{{ClientSSLProtocol}}"
    }
   ]
  }
 ]
}