{
 "title": "Grafana CI Code Stats",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "A11y Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(linearRegression(consolidateBy(grafana.ci-code.accessibilityErrors, 'min'), '-7d', 'now+1d'), 'trend')"
    },
    {
     "target": "alias(consolidateBy(grafana.ci-code.accessibilityErrors, 'min'), 'errors')"
    }
   ]
  },
  {
   "title": "A11y Errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(grafana.ci-code.accessibilityErrors, 'min')"
    }
   ]
  },
  {
   "title": "Betterer: no-explicit-any",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(consolidateBy(grafana.ci-code.strictLint.noExplicitAny, 'min'), 'errors')"
    },
    {
     "target": "alias(consolidateBy(grafana.ci-code.betterer.betterEslint_unexpectedAnySpecifyADifferentType, 'min'), 'errors')"
    }
   ]
  },
  {
   "title": "Betterer: no-explicit-any",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(grafana.ci-code.strictLint.noExplicitAny, 'min')"
    },
    {
     "target": "consolidateBy(grafana.ci-code.betterer.betterEslint_unexpectedAnySpecifyADifferentType, 'min')"
    }
   ]
  },
  {
   "title": "Betterer: no-explicit-any change in value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "target": "consolidateBy(grafana.ci-code.strictLint.noExplicitAny, 'min')"
    },
    {
     "target": "consolidateBy(grafana.ci-code.betterer.betterEslint_unexpectedAnySpecifyADifferentType, 'min')"
    }
   ]
  },
  {
   "title": "Betterer: no-type-assertions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(consolidateBy(grafana.ci-code.betterer.betterEslint_doNotUseAnyTypeAssertions, 'min'), 'errors')"
    }
   ]
  },
  {
   "title": "Betterer: no-type-assertions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(grafana.ci-code.betterer.betterEslint_doNotUseAnyTypeAssertions, 'min')"
    }
   ]
  },
  {
   "title": "Betterer: no-type-assertions change in value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "target": "consolidateBy(grafana.ci-code.betterer.betterEslint_doNotUseAnyTypeAssertions, 'min')"
    }
   ]
  },
  {
   "title": "Directives",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "grafana.ci-code.directives" }
   ]
  },
  {
   "title": "Directives",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "grafana.ci-code.directives" }
   ]
  },
  {
   "title": "Controllers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "grafana.ci-code.controllers" }
   ]
  },
  {
   "title": "Controllers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "grafana.ci-code.controllers" }
   ]
  },
  {
   "title": "Undocumented stories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(diffSeries(grafana.ci-code.grafana-ui.stories, #B), 'Undocumented stories')",
     "targetFull": "alias(diffSeries(grafana.ci-code.grafana-ui.stories, grafana.ci-code.grafana-ui.mdx), 'Undocumented stories')"
    },
    {
     "refCount": 1,
     "target": "alias(grafana.ci-code.betterer.noUndocumentedStories_noUndocumentedStoriesAreAllowedPleaseAddAnMdxFileWithSomeDocumentation, 'Undocumented stories')"
    }
   ]
  },
  {
   "title": "Undocumented stories",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(diffSeries(grafana.ci-code.grafana-ui.stories, #B), 'Undocumented stories')",
     "targetFull": "alias(diffSeries(grafana.ci-code.grafana-ui.stories, grafana.ci-code.grafana-ui.mdx), 'Undocumented stories')"
    },
    {
     "refCount": 1,
     "target": "alias(grafana.ci-code.betterer.noUndocumentedStories_noUndocumentedStoriesAreAllowedPleaseAddAnMdxFileWithSomeDocumentation, 'Undocumented stories')"
    }
   ]
  },
  {
   "title": "Legacy forms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "grafana.ci-code.legacyForms" }
   ]
  },
  {
   "title": "Legacy forms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "grafana.ci-code.legacyForms" }
   ]
  },
  {
   "title": "Bundle folder size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "target": "grafana.ci-code.bundleFolderSize"
    }
   ]
  },
  {
   "title": "Bundle folder size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "grafana.ci-code.bundleFolderSize"
    }
   ]
  },
  {
   "title": "Outdated dependencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(grafana.ci-code.dependencies.outdated, 'Outdated dependencies')"
    }
   ]
  },
  {
   "title": "Outdated dependencies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "grafana.ci-code.dependencies.outdated"
    }
   ]
  },
  {
   "title": "Dependency vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByMetric(grafana.ci-code.dependencies.vulnerabilities.critical)"
    },
    {
     "target": "aliasByMetric(grafana.ci-code.dependencies.vulnerabilities.high)"
    },
    {
     "target": "aliasByMetric(grafana.ci-code.dependencies.vulnerabilities.medium)"
    },
    {
     "target": "aliasByMetric(grafana.ci-code.dependencies.vulnerabilities.low)"
    }
   ]
  },
  {
   "title": "Dependency vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(grafana.ci-code.dependencies.vulnerabilities.*)"
    }
   ]
  },
  {
   "title": "CI Performance Frontend Tests (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "grafana.ci-performance.frontend-tests"
    }
   ]
  },
  {
   "title": "Frontend build time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 86 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(grafana.ci-performance.frontend-build, 'min'), 'time frontend build')"
    }
   ]
  },
  { "title": "Archived", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Strict Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(linearRegression(consolidateBy(grafana.ci-code.strictErrors, 'min'), '-7d', 'now+1d'), 'trend')"
    },
    {
     "target": "alias(consolidateBy(grafana.ci-code.strictErrors, 'min'), 'errors')"
    }
   ]
  },
  {
   "title": "Strict Errors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "consolidateBy(grafana.ci-code.strictErrors, 'min')"
    }
   ]
  },
  {
   "title": "Number of Enzyme test files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(grafana.ci-code.enzymeTests, 'numEnzymeTests')"
    },
    {
     "target": "alias(grafana.ci-code.betterer.noEnzymeTests_regExpMatch, 'numEnzymeTests')"
    }
   ]
  },
  {
   "title": "Number of Enzyme test files",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "grafana.ci-code.enzymeTests" },
    {
     "target": "grafana.ci-code.betterer.noEnzymeTests_regExpMatch"
    }
   ]
  }
 ]
}