{
 "title": "Native Histogram",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Heatmap Old histograms",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rpc_durations_histogram_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Percentile 95 75 & 50",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(rpc_durations_histogram_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(rpc_durations_histogram_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(rpc_durations_histogram_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Delta to real value",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "abs(histogram_quantile(0.95, sum by(le) (rate(rpc_durations_histogram_seconds_bucket[$__rate_interval]))) - 4.29)",
     "legendFormat": "P95"
    },
    {
     "expr": "abs(histogram_quantile(0.75, sum by(le) (rate(rpc_durations_histogram_seconds_bucket[$__rate_interval]))) - 2.35 )",
     "legendFormat": "P75"
    },
    {
     "expr": "abs(histogram_quantile(0.5, sum by(le) (rate(rpc_durations_histogram_seconds_bucket[$__rate_interval]))) - 1)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Heatmap Native histograms",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(rpc_durations_native_histogram_seconds[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile 95 75 & 50",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(rpc_durations_native_histogram_seconds[$__rate_interval]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.75, rate(rpc_durations_native_histogram_seconds[$__rate_interval]))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.5, rate(rpc_durations_native_histogram_seconds[$__rate_interval]))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Delta to real value",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "abs(histogram_quantile(0.95, (rate(rpc_durations_native_histogram_seconds_bucket[$__rate_interval]))) - 4.29)",
     "legendFormat": "P95"
    },
    {
     "expr": "abs(histogram_quantile(0.75, sum by(le) (rate(rpc_durations_native_histogram_seconds_bucket[$__rate_interval]))) - 2.35 )",
     "legendFormat": "P75"
    },
    {
     "expr": "abs(histogram_quantile(0.5, sum by(le) (rate(rpc_durations_native_histogram_seconds_bucket[$__rate_interval]))) - 1)",
     "legendFormat": "Mean"
    }
   ]
  }
 ]
}