{
 "title": "#3796 8w Trendline bug when joining between Google Sheets and Salesforce",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "User_State",
    "label": "State",
    "query": "{\"find\": \"terms\", \"field\": \"user_state.keyword\", \"size\":200}"
   },
   {
    "name": "procedure_id",
    "query": "{\"find\": \"terms\", \"field\": \"procedure_id.keyword\", \"size\":55}"
   },
   {
    "name": "b2bcode",
    "query": "{\"find\": \"terms\", \"field\": \"b2bcode\", \"size\":200}"
   },
   {
    "name": "fulfillmentcenter",
    "query": "{\"find\": \"terms\", \"field\": \"fulfillmentcenter\", \"size\":200}"
   },
   { "name": "t2t_provider", "query": "GGM,WHEEL,WheelT2TProvider" }
  ]
 },
 "panels": [
  {
   "title": "# Test Units Sold",
   "type": "stat",
   "description": "Units sold across both Ecomm systems.\n\nCurrenlty only valid for June",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "builderOptions": { "fields": [ "FIELDS(STANDARD)" ], "limit": 100, "mode": "list", "table": "Opportunity" },
     "soql": "SELECT SUM(Quantity),Product2.StockKeepingUnit FROM OrderItem\nWHERE type='Order Product' AND Order.ActivatedDate > $__timeFrom AND Order.ActivatedDate < $__timeTo\nAND Product2.StockKeepingUnit != 'EMED-195100' AND Order.Type != 'Replacement Order'\nGROUP BY Product2.StockKeepingUnit"
    },
    {
     "builderOptions": { "fields": [ "FIELDS(STANDARD)" ], "limit": 100, "mode": "list", "table": "Opportunity" },
     "cacheDurationSeconds": 300,
     "soql": "SELECT FIELDS(STANDARD) FROM Opportunity LIMIT 100",
     "spreadsheet": "1PaeRc5FDxKNGWcJK6kxGCrwFxbBoNy1fJ4CJGo04bUw"
    }
   ]
  },
  {
   "title": "Total Orders",
   "type": "stat",
   "description": "Total of 6 Pack order. Fullfullmentcenter and B2BCode filter doesn't applied here.\n\nCurrently only valid for June",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "builderOptions": { "fields": [ "FIELDS(STANDARD)" ], "limit": 100, "mode": "list", "table": "Opportunity" },
     "soql": "SELECT count(Id) from Order \nWHERE ActivatedDate > $__timeFrom AND ActivatedDate < $__timeTo\nAND Type != 'Replacement Order'"
    }
   ]
  },
  {
   "title": "Vlab2 % Proctor Paired <= 60 sec",
   "type": "gauge",
   "description": "Percentage of queued sessions that were picked up by a proctor within 60s",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND _exists_:procedure_id AND procedure_id:\"$procedure_id\" ",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND queue_duration:<60 AND _exists_:procedure_id AND procedure_id:\"$procedure_id\" ",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Current Wait Time",
   "type": "stat",
   "description": "Current wait time on English Queue - average longest wait in the last 5m",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "English Proctor Queue"
     },
     "metricName": "LongestQueueWaitTime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "region": "default",
     "statistic": "Average",
     "timeField": "session_created_at"
    }
   ]
  },
  {
   "title": "Reason For Testing",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": {
        "filters": [
         {
          "label": "Travel",
          "query": "reason_testing:\"international-travel\""
         },
         {
          "label": "School",
          "query": "reason_testing:\"for-school\""
         },
         {
          "label": "Work",
          "query": "reason_testing:\"for-work\""
         },
         {
          "label": "Sick",
          "query": "reason_testing:\"feeling-sick\""
         },
         {
          "label": "Wants Treatment",
          "query": "reason_testing:\"wants-treatment\""
         },
         {
          "label": "Other",
          "query": "reason_testing:\"for-other\""
         },
         {
          "label": "Event",
          "query": "reason_testing:\"for-event\""
         },
         { "label": "NULL", "query": "NOT _exists_:reason_testing" }
        ]
       },
       "type": "filters"
      },
      { "field": "first_connected_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Vlab2 Survey Completion Percentage",
   "type": "gauge",
   "description": "Percent of completed sessions where a user rated the proctor.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND survey_stars:[1 TO 5] AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "description": "Total sessions that ended with a positive, negative, inconclusive, or other (could-not-finish) result.",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Total Units Sold Per Day",
   "type": "timeseries",
   "description": "Total number of tests sold per day, separated into how many individual tests where sold in a 6-pack config and how many \nwhere sold in a 2-pack config. America/New York Timezone.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "connectionArgs": { "catalog": "__default", "database": "__default", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "SELECT DATE_TRUNC('day', activated_at AT TIME ZONE 'America/New_York') AS Date, SKU, SUM(Units) Units\nFROM (\n    SELECT activated_at\n      , CASE p.SKU WHEN 'EMED-195102' THEN '2 Pack' WHEN 'EMED-195201' THEN '6 Pack' ELSE '6 Pack' END as SKU\n      , oi.Quantity * p.testkit_quantity AS Units\n    FROM default.emed_order_silver o\n        INNER JOIN order_salesforce.emed_orderitems oi\n            ON o.id = oi.orderid\n        INNER JOIN order_salesforce.emed_products p\n            ON oi.productid = p.id\n    WHERE o.ecomm = 'eComm2'\n        AND lower(o.status) IN ('to be fulfilled', 'awaiting shipment', 'shipped', 'created')\n        AND oi.type = 'Order Product'\n        AND p.sku != 'SHIP'\n        AND p.testkit_quantity IN (2, 6)\n        AND o.activated_at $__timeFilter\n    UNION ALL\n    SELECT created_at\n      , '6 Pack' AS SKU\n      , 6 AS Units\n    FROM default.emed_order o\n    WHERE lower(o.payment) != 'unpaid'\n        AND o.canceled_at is null\n        AND o.replace_of IS NULL\n        AND o.b2bcode is null\n        AND o.created_at $__timeFilter\n)\nGROUP BY 1, 2\nORDER BY 1",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "spreadsheet": "1eBHqlrQQWIsPSD1Rifvqpj5fUVWKgIgCYqLenrmgF5g",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Negative",
   "type": "stat",
   "description": "Number of Negative test results recorded and reported",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "result.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Negative AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Customers in Queue",
   "type": "stat",
   "description": "Current number of customers waiting in queue for a session\n\nNote that this is not filtered by a selected state",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "English Queue",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "English Proctor Queue"
     },
     "metricName": "QueueSize",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "region": "us-east-1",
     "statistic": "Maximum",
     "timeField": "session_created_at"
    },
    {
     "alias": "Spanish Queue",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "Spanish Proctor Queue"
     },
     "metricName": "QueueSize",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "region": "us-east-1",
     "statistic": "Maximum",
     "timeField": "session_created_at"
    }
   ]
  },
  {
   "title": "Vlab2 Number of Stars",
   "type": "bargauge",
   "description": "Number of 1, 2, 3, 4, or 5 star proctor ratings.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": {
        "filters": [
         { "label": "1*", "query": "survey_stars:1  " },
         { "label": "2*", "query": "survey_stars:2" },
         { "label": "3*", "query": "survey_stars:3" },
         { "label": "4*", "query": "survey_stars:4" },
         { "label": "5*", "query": "survey_stars:5" }
        ]
       },
       "type": "filters"
      },
      {
       "field": "survey_stars",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND _exists_:survey_stars AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Positive T2T",
   "type": "stat",
   "description": "Number of Positive test results recorded and reported",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      {
       "field": "result.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Positive AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_application:\"test-to-treat\" AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_application:\"test-to-treat\" AND _exists_:t2t_disposition AND NOT (t2t_disposition:\"return_from_consult\" OR t2t_disposition:\"questionnaire-in-progress\") AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Vlab2 Average Queue Wait Time ",
   "type": "timeseries",
   "description": "Rolling view of average queue wait times",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "English Proctor Queue",
     "bucketAggs": [
      { "field": "last_disconnected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "English Proctor Queue"
     },
     "metricName": "LongestQueueWaitTime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average",
     "timeField": "last_disconnected_at"
    },
    {
     "alias": "VIP Proctor Queue",
     "bucketAggs": [
      { "field": "last_disconnected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "VIP Proctor Queue"
     },
     "metricName": "LongestQueueWaitTime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average",
     "timeField": "last_disconnected_at"
    },
    {
     "alias": "Spanish Proctor Queue",
     "bucketAggs": [
      { "field": "last_disconnected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "Spanish Proctor Queue"
     },
     "metricName": "LongestQueueWaitTime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average",
     "timeField": "last_disconnected_at"
    },
    {
     "alias": "BNC-Govt Spanish Proctor Queue",
     "bucketAggs": [
      { "field": "last_disconnected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "bnc-govt-es"
     },
     "metricName": "LongestQueueWaitTime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average",
     "timeField": "last_disconnected_at"
    },
    {
     "alias": "BNC-Govt English Proctor Queue",
     "bucketAggs": [
      { "field": "last_disconnected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "bnc-govt-en"
     },
     "metricName": "LongestQueueWaitTime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average",
     "timeField": "last_disconnected_at"
    },
    {
     "alias": "covid-247ai-english",
     "bucketAggs": [
      { "field": "last_disconnected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "covid-247ai-english"
     },
     "metricName": "LongestQueueWaitTime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average",
     "timeField": "last_disconnected_at"
    },
    {
     "alias": "Lucira English",
     "bucketAggs": [
      { "field": "last_disconnected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "combo-en"
     },
     "metricName": "LongestQueueWaitTime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average",
     "timeField": "last_disconnected_at"
    },
    {
     "alias": "combo-iqor-english",
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "combo-iqor-english"
     },
     "metricName": "LongestQueueWaitTime",
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "wh-247ai-english",
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "wh-247ai-english"
     },
     "metricName": "LongestQueueWaitTime",
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "wh-sitel-english",
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "wh-sitel-english"
     },
     "metricName": "LongestQueueWaitTime",
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "combo-sitel-english",
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "combo-sitel-english"
     },
     "metricName": "LongestQueueWaitTime",
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "wh-iqor-english",
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "wh-iqor-english"
     },
     "metricName": "LongestQueueWaitTime",
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "covid-iqor-english",
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "covid-iqor-english"
     },
     "metricName": "LongestQueueWaitTime",
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "covid-sitel-english",
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "covid-sitel-english"
     },
     "metricName": "LongestQueueWaitTime",
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "covid-sitel-spanish",
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "covid-sitel-spanish"
     },
     "metricName": "LongestQueueWaitTime",
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "InstanceId": "a2addf6e-7d0f-4688-8311-60b22152fd85",
      "MetricGroup": "Queue",
      "QueueName": "covid-vip-english"
     },
     "metricName": "LongestQueueWaitTime",
     "namespace": "AWS/Connect",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "description": "Sessions in progress where an ECG is proctoring a patient in Vlab2",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "event_date", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND session_is_started:true AND session_is_finished:false AND time:[\"now-60m\" TO \"now\"] AND procedure_id:\"$procedure_id\"",
     "timeField": "event_date"
    }
   ]
  },
  {
   "title": "Average Contact Count",
   "type": "stat",
   "description": "Average Contact per session group by sessions with results",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "result.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "contact_id_count", "id": "1", "type": "avg" }
     ],
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Vlab2 Proctor Survey, Avg Star Rating",
   "type": "stat",
   "description": "Average proctor star rating from end-of-session survey.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "first_connected_at",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "America/New_York", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "survey_stars", "id": "1", "type": "avg" }
     ],
     "query": "user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "% Unit Sales per SKU",
   "type": "timeseries",
   "description": "Percentage of tests sold per day, separated into how many individual tests were sold in a 6-pack config and how many were sold in a 2-pack config. America/New_York timezone",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "builderOptions": { "fields": [ "FIELDS(STANDARD)" ], "limit": 100, "mode": "list", "table": "Opportunity" },
     "soql": "SELECT DAY_ONLY(Order.ActivatedDate),SUM(Quantity),Product2.StockKeepingUnit FROM OrderItem\nWHERE type='Order Product' AND Order.ActivatedDate > 2022-05-01T00:00:00Z AND Order.ActivatedDate < $__timeTo\nAND Product2.StockKeepingUnit != 'EMED-195100'\nGROUP BY DAY_ONLY(Order.ActivatedDate),Product2.StockKeepingUnit"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "cacheDurationSeconds": 300,
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "spreadsheet": "1PaeRc5FDxKNGWcJK6kxGCrwFxbBoNy1fJ4CJGo04bUw",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "* Sessions Per Hour (Average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Mobile Usage",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "3",
       "settings": {
        "filters": [
         { "label": "Mobile", "query": "ismobile:true" },
         { "label": "Desktop", "query": "ismobile:false" }
        ]
       },
       "type": "filters"
      },
      { "field": "event_date", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "event_date"
    }
   ]
  },
  {
   "title": "* Invalid",
   "type": "stat",
   "description": "Number of Invalid test results recorded and reported",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "result.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Invalid AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "* Other",
   "type": "stat",
   "description": "Number of Other test results recorded and reported. These are sessions where a test was consumed, but a result could not be obtained (ex. test dropped on floor, etc.) ",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Other AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Orders & Payment Method",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "activated_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "builderOptions": { "fields": [ "FIELDS(STANDARD)" ], "limit": 100, "mode": "list", "table": "Opportunity" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "soql": "SELECT Payment_System__c Payment, count(Id) total_count FROM Order \nWHERE ActivatedDate > $__timeFrom AND ActivatedDate < $__timeTo\nAND (Payment_System__c != '')\nGROUP BY Payment_System__c",
     "timeField": "activated_at"
    }
   ]
  },
  {
   "title": "Unique User (Total Emails)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "column": "email",
     "connectionArgs": { "catalog": "__default", "database": "__default", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "select count(distinct email) from emed_users",
     "table": "emed_users",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "NAVICA Users (Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "column": "navica_id",
     "connectionArgs": { "catalog": "__default", "database": "__default", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "select count(distinct navica_id) from emed_users",
     "table": "emed_users",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "*Sessions",
   "type": "graph",
   "description": "Number of Completed and Started Sessions per day",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Session Started",
     "bucketAggs": [
      { "field": "event_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "event_date"
    },
    {
     "alias": "Session Completed",
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "7 day Moving Average",
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      },
      {
       "field": "1",
       "id": "3",
       "pipelineAgg": "1",
       "settings": { "model": "simple", "window": "7" },
       "type": "moving_avg"
      }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Users That Tested",
   "type": "stat",
   "description": "Number of Unique Users that have taken a test",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "column": "user_id",
     "connectionArgs": { "catalog": "__default", "database": "__default", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "select count(distinct user_id) from ftf_core_sessions_result_nopii ",
     "table": "ftf_core_prod_all",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "% NAVICA ",
   "type": "stat",
   "description": "% of how many sessions with result that login with Navica or eMed group by day for the past 8 weeks",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "3",
       "settings": {
        "filters": [
         { "label": "Navica Login", "query": "_exists_:navica_profile_id" },
         { "label": "eMed Login", "query": "NOT _exists_:navica_profile_id" }
        ]
       },
       "type": "filters"
      },
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Trends",
   "type": "text",
   "gridPos": { "h": 1, "w": 23, "x": 0, "y": 23 },
   "options": { "content": " " },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  shipweight\nFROM orders\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total SKUs Sold ",
   "type": "timeseries",
   "description": "Number of Test Kit sold each day by SKU",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "6 Pack",
     "bucketAggs": [
      { "field": "activated_at", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Quantity", "id": "1", "type": "sum" }
     ],
     "query": "product_quantity:6 AND (((status:\"To Be Fulfilled\" OR status:\"Awaiting shipment\" OR status:\"Shipped\" OR status:\"Created\") AND eComm:eComm2) OR (NOT payment:unpaid AND NOT _exists_:canceled_at AND eComm:eComm1))",
     "timeField": "activated_at"
    },
    {
     "alias": "2 Pack",
     "bucketAggs": [
      { "field": "activated_at", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Quantity", "id": "1", "type": "sum" }
     ],
     "query": "product_quantity:2 AND (((status:\"To Be Fulfilled\" OR status:\"Awaiting shipment\" OR status:\"Shipped\" OR status:\"Created\") AND eComm:eComm2) OR (NOT payment:unpaid AND NOT _exists_:canceled_at AND eComm:eComm1))",
     "timeField": "activated_at"
    }
   ]
  },
  {
   "title": "Star Rating %",
   "type": "timeseries",
   "description": "Star Rating %",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "survey_stars",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      { "field": "last_connected_at", "id": "11", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND _exists_:survey_stars",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "last_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND _exists_:survey_stars",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Reason For Testing %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": {
        "filters": [
         {
          "label": "Travel",
          "query": "reason_testing:\"international-travel\""
         },
         {
          "label": "School",
          "query": "reason_testing:\"for-school\""
         },
         {
          "label": "Work",
          "query": "reason_testing:\"for-work\""
         },
         {
          "label": "Sick",
          "query": "reason_testing:\"feeling-sick\""
         },
         {
          "label": "Wants Treatment",
          "query": "reason_testing:\"wants-treatment\""
         },
         {
          "label": "Other",
          "query": "reason_testing:\"other-reason\""
         },
         {
          "label": "Event",
          "query": "reason_testing:\"for-event\""
         },
         {
          "label": "None",
          "query": "reason_testing:\"none\""
         },
         { "label": "NULL", "query": "NOT _exists_:reason_testing" }
        ]
       },
       "type": "filters"
      },
      { "field": "first_connected_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Average Results per Hour per Proctor",
   "type": "graph",
   "description": "Total results / total proctors  in 1 hour buckets.",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Total Results",
     "bucketAggs": [
      { "field": "last_connected_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Unique Proctors",
     "bucketAggs": [
      {
       "field": "disconnecttimestamp_date_format",
       "id": "2",
       "settings": { "interval": "auto" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "agent.username.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "attributes.procedureid:\"$procedure_id\"",
     "timeField": "disconnecttimestamp_date_format"
    }
   ]
  },
  {
   "title": "Positive to T2T Consult %",
   "type": "timeseries",
   "description": "How many people tested positive and how many people started a t2t consult during the last 8 weeks",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "begin_consult",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_application:\"test-to-treat\" AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Positive",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Positive AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Submitted",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_application:\"test-to-treat\" AND _exists_:t2t_disposition AND NOT t2t_disposition:\"return_from_consult\" AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Positive Non Traveler",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Positive AND user_state:$User_State AND NOT reason_testing:travel AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "begin_consult Non Traveler",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND NOT reason_testing:travel AND t2t_application:\"test-to-treat\" AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Submitted Non Traveler",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND NOT reason_testing:travel AND t2t_application:\"test-to-treat\" AND _exists_:t2t_disposition AND NOT t2t_disposition:\"return_from_consult\" AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Other Dashboards",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 31 },
   "options": {
    "content": "\n\n[User Demographics in Tableau](https://tableau-server.emed.com/views/SessionDemographics_16590229326280/SessionDemographics?:showAppBanner=false&:display_count=n&:showVizHome=n&:origin=viz_share_link)\n\n[Sessions Results in Tableau](https://tableau-server.emed.com/#/views/SessionResults/SessionsDashboard?:iid=4)\n           "
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "* % Burner Cards",
   "type": "gauge",
   "description": "Percentage of burner cards used for sessions",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Used Burner Cards",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "bc_used:true AND user_state:$User_State",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Results",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State ",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Burner Cards Remaining",
   "type": "stat",
   "description": "Count of unused burner cards\n\nNote this only includes burner cards since 2022-01-01\n\n",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "updated_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "used:false",
     "timeField": "updated_at"
    }
   ]
  },
  {
   "title": "Proctors Completing Calls",
   "type": "graph",
   "description": "Unique proctor usernames who completed at least one call during a 5 minute window",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "3",
       "settings": {
        "filters": [
         {
          "label": "Sitel",
          "query": "agent.username:*sitel.net* OR agent.username:*sykes*"
         },
         { "label": "eMed", "query": "agent.username:*emed.com" },
         { "label": "Iqor", "query": "agent.username:*iqor.com" },
         { "label": "247AI", "query": "agent.username:*247*" }
        ]
       },
       "type": "filters"
      },
      {
       "field": "disconnecttimestamp_date_format",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "agent.username.keyword", "id": "1", "type": "cardinality" }
     ],
     "timeField": "disconnecttimestamp_date_format"
    }
   ]
  },
  {
   "title": "New Users Per Month",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "column": "id",
     "connectionArgs": { "catalog": "__default", "database": "default", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "select \ndate_trunc('month',cast(created_at as date)) time,count(id) as Users\nfrom emed_users\nwhere $__dateFilter(created_at)\ngroup by date_trunc('month',cast(created_at as date))\norder by 1",
     "table": "emed_users",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Feedback",
   "type": "text",
   "gridPos": { "h": 1, "w": 23, "x": 0, "y": 44 },
   "options": { "content": " " },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  shipweight\nFROM orders\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Review Comments",
   "type": "table",
   "description": "Form feedback sorted by rating",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 45 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "_exists_:survey_stars AND _exists_:survey_comments AND user_state:$User_State AND survey_comments:/.{1}.*/ AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "5 Star Review Word Cloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "survey_comments",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "survey_stars:5 AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "1 Star Review Word Cloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 51 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "survey_comments",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "survey_stars:1 AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "4 Star Review Word Cloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "survey_comments",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "survey_stars:4 AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "2 Star Review Word Cloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 59 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "survey_comments",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "survey_stars:2 AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "3 Star Review Word Cloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "survey_comments",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "survey_stars:3 AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "NAVICA",
   "type": "text",
   "gridPos": { "h": 1, "w": 23, "x": 0, "y": 75 },
   "options": { "content": " " },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  shipweight\nFROM orders\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Results without Navica",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 76 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "_exists_:result AND NOT (procedure_id:binaxExpress OR procedure_id:quidel-covid OR procedure_id:sample OR procedure_id:abbott) AND NOT (_exists_:navica_status) AND _exists_:navica_profile_id",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Navica Accepted %",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "navica_status.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "last_connected_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Results Without Navica Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 20, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND NOT (procedure_id:binaxExpress OR procedure_id:quidel-covid OR procedure_id:sample OR procedure_id:abbott) AND NOT (_exists_:navica_status) AND _exists_:navica_profile_id",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Secondary",
   "type": "text",
   "gridPos": { "h": 1, "w": 23, "x": 0, "y": 85 },
   "options": { "content": " " },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  shipweight\nFROM orders\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Realtime Orders (30m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 86 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "eComm.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "activated_at",
       "id": "4",
       "settings": { "interval": "30m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(((status:\"To Be Fulfilled\" OR status:\"Awaiting shipment\" OR status:\"Shipped\" OR status:\"Created\") AND eComm:eComm2) OR (NOT payment:unpaid AND NOT _exists_:canceled_at AND eComm:eComm1))",
     "timeField": "activated_at"
    }
   ]
  },
  {
   "title": "Result Per Hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Negative Results",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Negative AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Positive Results",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Positive AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Invalid Results",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Invalid AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Other Results",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Other AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Results per Day",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 14, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Negative Results",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Negative AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Positive Results",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Positive AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Invalid Results",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Invalid AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Other Results",
     "bucketAggs": [
      { "field": "result_collected_by", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Other AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Proctors Online",
   "type": "graph",
   "description": "Unique proctor usernames who completed at least one call during the hour",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "3",
       "settings": {
        "filters": [
         { "label": "Sitel", "query": "agent.username:*sitel.net" },
         { "label": "eMed", "query": "agent.username:*emed.com" },
         { "label": "iqor", "query": "agent.username:*iqor.com" }
        ]
       },
       "type": "filters"
      },
      {
       "field": "disconnecttimestamp_date_format",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "agent.username.keyword", "id": "1", "type": "cardinality" }
     ],
     "timeField": "disconnecttimestamp_date_format"
    }
   ]
  },
  {
   "title": "Average Session Duration with Result",
   "type": "graph",
   "description": "Session total connected time, first queue wait, and the difference",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "last_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_connected_duration", "id": "1", "settings": { "script": "_value / 1000" }, "type": "avg" },
      { "field": "queue_duration", "id": "3", "type": "avg" }
     ],
     "query": "_exists_:result AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Unique Proctors Online Per Day",
   "type": "graph",
   "description": "Unique proctor usernames who completed at least one call during the hour",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "3",
       "settings": {
        "filters": [
         { "label": "Sitel", "query": "agent.username:*sitel.net" },
         { "label": "eMed", "query": "agent.username:*emed.com" },
         { "label": "Iqor", "query": "agent.username:*iqor.com" }
        ]
       },
       "type": "filters"
      },
      {
       "field": "disconnecttimestamp_date_format",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "agent.username.keyword", "id": "1", "type": "cardinality" }
     ],
     "timeField": "disconnecttimestamp_date_format"
    }
   ]
  },
  {
   "title": "Count of Star Ratings",
   "type": "timeseries",
   "description": "Rolling View of 1 and 5 Star Ratings",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "survey_stars",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "20m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Reason For Testing Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": {
        "filters": [
         {
          "label": "Travel",
          "query": "reason_testing:\"international-travel\""
         },
         {
          "label": "School",
          "query": "reason_testing:\"for-school\""
         },
         {
          "label": "Work",
          "query": "reason_testing:\"for-work\""
         },
         {
          "label": "Sick",
          "query": "reason_testing:\"feeling-sick\""
         },
         {
          "label": "Wants Treatment",
          "query": "reason_testing:\"wants-treatment\""
         },
         {
          "label": "Other",
          "query": "reason_testing:\"other-reason\""
         },
         {
          "label": "Event",
          "query": "reason_testing:\"for-event\""
         },
         { "label": "NULL", "query": "NOT _exists_:reason_testing" }
        ]
       },
       "type": "filters"
      },
      { "field": "created_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Staging",
   "type": "text",
   "gridPos": { "h": 1, "w": 23, "x": 0, "y": 111 },
   "options": { "content": " " },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  shipweight\nFROM orders\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "VIP Orders Used",
   "type": "text",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 112 },
   "options": {
    "content": "<iframe src=\"https://docs.google.com/spreadsheets/d/e/2PACX-1vTO2tIsc8_L0N_dXGFXd5OOcK6hMG1Ysc3VJaxYIUGCi6KAcjNLYfHawOJCffJU8jxv4YEPqFSzYbwC/pubchart?oid=1830282683&format=interactive\" title=\"VIP Orders Used\" style=\"width:100%; height:100%; padding:0; margin:0; border:none;\"></iframe>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "New Users Per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "column": "id",
     "connectionArgs": { "catalog": "__default", "database": "default", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "select \ncast(created_at as date),count(id) as Users\nfrom emed_users\nwhere $__dateFilter(created_at)\ngroup by cast(created_at as date)\norder by cast(created_at as date) asc",
     "table": "emed_users",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Total Sessions VS Repeat Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "column": "sessionid",
     "connectionArgs": { "catalog": "__default", "database": "default", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "select \ncast(created_at_ts as date),count(sessionid) as \"Total Sessions\", count(users.user_id) \"Repeated Users\"\nfrom ftf_core_sessions_result_nopii  sessions\nLEFT JOIN (SELECT user_id,count(sessionid) \nfrom ftf_core_sessions_result_nopii\nwhere $__dateFilter(created_at_ts) \ngroup by user_id\nhaving count(sessionid) > 1) users on sessions.user_id = users.user_id\nwhere $__dateFilter(created_at_ts)  \ngroup by cast(created_at_ts as date)\norder by 1 asc\n\n\n",
     "table": "ftf_core_prod_all",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Number Orders by eComm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "eComm.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "activated_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(((status:\"To Be Fulfilled\" OR status:\"Awaiting shipment\" OR status:\"Shipped\" OR status:\"Created\") AND eComm:eComm2) OR (NOT payment:unpaid AND NOT _exists_:canceled_at AND eComm:eComm1))",
     "timeField": "activated_at"
    }
   ]
  },
  {
   "title": "%  Navica Login vs eMed Login",
   "type": "timeseries",
   "description": "% of how many sessions with result that login with Navica or eMed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "3",
       "settings": {
        "filters": [
         { "label": "Navica Login", "query": "_exists_:navica_profile_id" },
         { "label": "eMed Login", "query": "NOT _exists_:navica_profile_id" }
        ]
       },
       "type": "filters"
      },
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Navica Login vs eMed Login",
   "type": "timeseries",
   "description": "Trend line of Count of  sessions with result that login with Navica or eMed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "3",
       "settings": {
        "filters": [
         { "label": "Navica Login", "query": "_exists_:navica_profile_id" },
         { "label": "eMed Login", "query": "NOT _exists_:navica_profile_id" }
        ]
       },
       "type": "filters"
      },
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "% Quantity of Test Units Sold per Order",
   "type": "piechart",
   "description": "A breakdown of the total test units sold by the quantity ordered.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "TotalUnity",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "activated_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TotalUnity", "id": "1", "type": "sum" }
     ],
     "query": "(((status:\"To Be Fulfilled\" OR status:\"Awaiting shipment\" OR status:\"Shipped\" OR status:\"Created\") AND eComm:eComm2) OR (NOT payment:unpaid AND NOT _exists_:canceled_at AND eComm:eComm1))",
     "timeField": "activated_at"
    }
   ]
  },
  {
   "title": "% Salesforce Order Quantity",
   "type": "piechart",
   "description": "% of Quantity of packages of the orders created during the time period selected group by day.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Quantity",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT payment:unpaid AND NOT _exists_:canceled_at AND eComm:eComm2",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Total Revenue (eCommerce)",
   "type": "stat",
   "description": "Units sold across both Ecomm systems.\n\nCurrenlty only valid for June",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "activated_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "builderOptions": { "fields": [ "FIELDS(STANDARD)" ], "limit": 100, "mode": "list", "table": "Opportunity" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "soql": "SELECT GrandTotalAmount, TotalTaxAmount, TotalAdjustedDeliveryAmount FROM Order \nWHERE ActivatedDate > $__timeFrom AND ActivatedDate < $__timeTo\nAND Type != 'Replacement Order'",
     "timeField": "activated_at"
    }
   ]
  },
  {
   "title": "Positives Redirected",
   "type": "stat",
   "description": "Count of positive test takers that have an FTF Redirect URL and do not get routed to test to treat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 146 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "3",
       "settings": {
        "filters": [
         { "label": "FTF Override", "query": "_exists_:redirectURL" }
        ]
       },
       "type": "filters"
      },
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Positive AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Abandoned Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "disconnecttimestamp_date_format",
       "id": "2",
       "settings": { "interval": "auto" },
       "type": "date_histogram"
      }
     ],
     "column": "session_id",
     "connectionArgs": { "catalog": "__default", "database": "connect-prod", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "select date_trunc('day',disconnecttimestamp),count(distinct session_id) as \"Abandoned Sessions\" from ctr_abandoned_contacts\nwhere $__timeFilter(disconnecttimestamp)\nAND session_id NOT IN (select session_id from ctr_abandoned_contacts where agent_username is NOT NULL and $__timeFilter(disconnecttimestamp))\ngroup by date_trunc('day',disconnecttimestamp)\norder by 1",
     "table": "ctr_events_failed_connect",
     "timeField": "disconnecttimestamp_date_format"
    }
   ]
  },
  {
   "title": "new Unique Users last 7 days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "connectionArgs": { "catalog": "__default", "database": "__default", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "select \ncount(distinct email)\ncreated_at\nfrom emed_users \nwhere created_at > current_date - interval '7' day",
     "table": "emed_users",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Process Flow",
   "type": "jdbranham-diagram-panel",
   "description": "Total Sessions Started - Total number of sessions users initiated (i.e. entered the queue)\n\nPatient and Proctor Connected - Patient and Proctor joined into a session together\n\nCustomers in Queue - Current number of customers waiting in queue for a session\n\nUser Left Queue - User left before the proctor picked up\n\nActive Sessions - Sessions in progress where an ECG is proctoring a patient\n\nCompleted With Result - Total sessions that ended with a positive, negative, inconclusive, or other (could-not-finish) result\n\nEnded Unexpectedly - Total number of sessions that were initiated (a proctor joined) but which ended via an unhappy path (a proctor did not use End Call or submit a result)\n\nOther Drops - Sessions that ended for any other reason\n\nResult (Negative) - Number of Negative test results recorded and reported\n\nResult (Positive) - Number of Positive test results recorded and reported\n\nResult (Invalid) - Number of Invalid test results recorded and reported\n\nResult (Other) - Number of Other test results recorded and reported. These are sessions where a test was consumed, but a result could not be obtained (ex. test dropped on floor, etc.)",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 157 },
   "options": {
    "content": "graph LR\n      Total_Sessions_Started(Total Sessions Started) ==> Patient_and_Proctor_Connected(Patient and Proctor Connected)\n      Total_Sessions_Started(Total Sessions Started) --> Customers_in_Queue(Customers in Queue)\n      Total_Sessions_Started(Total Sessions Started) --> User_Left_Queue(User Left Queue)\n      Patient_and_Proctor_Connected(Patient and Proctor Connected) --> Active_Sessions(Active Sessions)\n      Patient_and_Proctor_Connected(Patient and Proctor Connected) ==> Completed_With_Result(Completed With Result)\n      Completed_With_Result(Completed With Result) ==> Result_Negative(Result - Negative)\n      Completed_With_Result(Completed With Result) ==> Result_Positive(Result - Positive)\n      Completed_With_Result(Completed With Result) ==> Result_Invalid(Result - Invalid)\n      Completed_With_Result(Completed With Result) ==> Result_Other(Result - Other)\n      Patient_and_Proctor_Connected(Patient and Proctor Connected) --> Ended_Unexpectedly(Ended Unexpectedly)\n      Patient_and_Proctor_Connected(Patient and Proctor Connected) --> test_expired(Test Expired)\nPatient_and_Proctor_Connected(Patient and Proctor Connected) --> Indentity_Failed(Indentity Failed)\n\nResult_Positive(Result-Positive) --> \nGoGoMedTotalSessions(Go-Go-Med-Total-Sessions)\n\nGoGoMedTotalSessions(Go-Go-Med-Total-Sessions)-->Completed_GoGo(Completed GoGo)\n\nCompleted_GoGo(Completed GoGo)-->\nRX_GoGo(RX)\n\nResult_Positive(Result-Positive) --> \nWheelTotalSessions(Wheel-Total-Sessions)\n\nWheelTotalSessions(Wheel-Total-Sessions)--> \nCompleted_Wheel(Completed)\n\nCompleted_Wheel(Completed)--> \nRX_Wheel(RX)\n\n\n\n      classDef default color:#bbe1fa,fill:#1b262c,stroke:#0f4c75,stroke-width:4px;\n      style test_expired color:#c02739\n      style Indentity_Failed color:#c02739\n      style Ended_Unexpectedly color:#c02739\n      style User_Left_Queue color:#c02739"
   },
   "targets": [
    {
     "alias": "Total Sessions Started",
     "bucketAggs": [
      {
       "field": "event_date",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "America/New_York", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "time"
    },
    {
     "alias": "User Left Queue",
     "bucketAggs": [
      { "field": "event_date", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "checkpoint:queue_connecting AND NOT checkpoint:queue_connected AND time:[\"*\" TO \"now-60m\"] AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "time"
    },
    {
     "alias": "Customers in Queue",
     "bucketAggs": [
      { "field": "event_date", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "checkpoint:queue_connecting AND NOT checkpoint:queue_connected AND time:[\"now-10m\" TO \"now\"] AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "time"
    },
    {
     "alias": "Patient and Proctor Connected",
     "bucketAggs": [
      { "field": "event_date", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "checkpoint:queue_connected AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "time"
    },
    {
     "alias": "Active Sessions",
     "bucketAggs": [
      { "field": "event_date", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(checkpoint:test_started OR checkpoint:test_consumed OR checkpoint:sample_collected) AND NOT checkpoint:test_finished AND time:[\"now-60m\" TO \"now\"] AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "time"
    },
    {
     "alias": "Completed With Result",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Ended Unexpectedly",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT _exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "test_expired",
     "bucketAggs": [
      {
       "field": "event_date",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "America/New_York", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "checkpoint:test_expired AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "time"
    },
    {
     "alias": "Indentity_Failed",
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "checkpoint:identity_failed AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "time"
    },
    {
     "alias": "Result_Negative",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Negative AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Result_Positive",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Positive AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Result_Other",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Other AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Result_Invalid",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "1d", "timeZone": "America/New_York" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Invalid AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "GoGoMedTotalSessions",
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:GGM AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "WheelTotalSessions",
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:WHEEL AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "Completed_GoGo",
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:GGM AND _exists_:t2t_disposition AND NOT t2t_disposition:\"return_from_consult\" AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "RX_GoGo",
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:GGM AND (t2t_disposition:Prescribed OR t2t_disposition:finish-prescribed) AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "alias": "RX_Wheel",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "time"
    },
    {
     "alias": "Completed_Wheel",
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:WHEEL AND _exists_:t2t_disposition AND NOT t2t_disposition:\"return_from_consult\" AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Positive GGM",
   "type": "stat",
   "description": "Number of Positive test results recorded and reported",
   "gridPos": { "h": 12, "w": 2, "x": 1, "y": 171 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      {
       "field": "result.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Positive AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:GGM AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:GGM AND _exists_:t2t_disposition AND NOT (t2t_disposition:\"return_from_consult\" OR t2t_disposition:\"questionnaire-in-progress\") AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:GGM AND (t2t_disposition:Prescribed OR t2t_disposition:finish-prescribed) AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "Positive WHEEL",
   "type": "stat",
   "description": "Number of Positive test results recorded and reported",
   "gridPos": { "h": 12, "w": 2, "x": 3, "y": 171 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:result AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      {
       "field": "created_at",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "result:Positive AND user_state:$User_State AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:WHEEL AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_provider:WHEEL AND _exists_:t2t_disposition AND NOT t2t_disposition:\"return_from_consult\" AND procedure_id:\"$procedure_id\"",
     "timeField": "first_connected_at"
    },
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Abandoned Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "disconnecttimestamp_date_format",
       "id": "2",
       "settings": { "interval": "auto" },
       "type": "date_histogram"
      }
     ],
     "column": "session_id",
     "connectionArgs": { "catalog": "__default", "database": "connect-prod", "region": "__default" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSQL": "select date_trunc('day',disconnecttimestamp),count(distinct session_id) as \"Abandoned Sessions\" from ctr_abandoned_contacts\nwhere $__timeFilter(disconnecttimestamp)\nAND session_id NOT IN (select session_id from ctr_abandoned_contacts where agent_username is NOT NULL and $__timeFilter(disconnecttimestamp))\ngroup by date_trunc('day',disconnecttimestamp)\norder by 1",
     "table": "ctr_events_failed_connect",
     "timeField": "disconnecttimestamp_date_format"
    }
   ]
  },
  {
   "title": "T2T avg consult duration",
   "type": "timeseries",
   "description": "Calculation was done by the difference between the min and max time for each consultid recorded on core",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "t2t_provider.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "first_connected_at",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "t2t_avg", "id": "1", "type": "avg" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_application:\"test-to-treat\" AND NOT t2t_provider:\"NA\" AND procedure_id:\"$procedure_id\" ",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "T2T Daily average Handle Time",
   "type": "timeseries",
   "description": "Calculation was done by the difference between the min and max time for each consultid recorded on core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "t2t_provider.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "t2t_avg", "id": "1", "type": "avg" }
     ],
     "query": "(result:Positive OR last_sync_id:positive_close) AND user_state:$User_State AND t2t_application:\"test-to-treat\" AND NOT t2t_provider:\"NA\" AND procedure_id:\"$procedure_id\" ",
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "New Test Completed Sessions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 191 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "New Tests Completed Sessions",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 191 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "lab.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Drug Test ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 198 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "lab:\"premierbiotech-oraltox8-multi\"",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "UTI Test",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 198 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "lab:\"teco-teststrip-uti\"",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "VPH",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 198 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "lab:\"teco-obgyn-vph\"",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Sessions Details",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 204 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "first_connected_at"
    }
   ]
  },
  {
   "title": "B2B Sales Quantity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "first_connected_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "builderOptions": {
      "fields": [ "FIELDS(STANDARD)" ],
      "filters": [
       {
        "condition": "AND",
        "filterType": "custom",
        "key": "StageName",
        "operator": "=",
        "type": "picklist",
        "value": "Closed Won"
       }
      ],
      "limit": 100,
      "metrics": [
       { "aggregation": "sum", "alias": "total_count", "field": "TotalOpportunityQuantity" }
      ],
      "mode": "trend",
      "table": "Opportunity",
      "timeField": "CreatedDate",
      "timeFieldType": "datetime"
     },
     "entity": "00O8c00000BaGPKEA3",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "report": { "id": "00O8c00000BaGPKEA3" },
     "soql": "SELECT DAY_ONLY(CreatedDate), sum(TotalOpportunityQuantity) total_count FROM Opportunity WHERE CloseDate >= $__timeFrom AND CloseDate <= $__timeTo AND   ( StageName = 'Closed Won' ) \nGROUP BY DAY_ONLY(CreatedDate) ",
     "timeField": "first_connected_at"
    }
   ]
  }
 ]
}