{
 "title": "#54872 Data links not always rendering",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespaceRegex", "query": ".*" },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(group by (namespace) (kube_namespace_created{namespace=~\".*$namespaceRegex.*\"}))"
    }
   },
   {
    "name": "alertname",
    "query": {
     "query": "query_result(group by (alertname) (count_over_time(ALERTS{namespace=~\"$namespace\"}[$__range]))or group by (alertname) (count_over_time(ALERTS{exported_namespace=~\"$namespace\"}[$__range])))"
    }
   },
   { "name": "severity", "query": "critical,warning" }
  ]
 },
 "panels": [
  { "title": "Combined view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "By alert name: $namespace",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(group by (alertname) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"critical\", severity=~\"$severity\", alertname=~\"$alertname\"}) + 1)\nor\n(group by (alertname) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"warning\", severity=~\"$severity\", alertname=~\"$alertname\"}))",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "By namespace: $namespace",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(group by (namespace) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"critical\", severity=~\"$severity\", alertname=~\"$alertname\"}) + 1)\nor\n(group by (namespace) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"warning\", severity=~\"$severity\", alertname=~\"$alertname\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Per-namespace view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$namespace",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "repeat": "namespace",
   "targets": [
    {
     "expr": "(group by (alertname) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"critical\", severity=~\"$severity\", alertname=~\"$alertname\"}) + 1)\nor\n(group by (alertname) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"warning\", severity=~\"$severity\", alertname=~\"$alertname\"}))",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  { "title": "Alert Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Volume by alert",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "(count by (alertname) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"critical\", severity=~\"$severity\", alertname=~\"$alertname\"}))\nor\n(count by (alertname) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"warning\", severity=~\"$severity\", alertname=~\"$alertname\"}))",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Volume by namespace",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "(count by (namespace) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"critical\", severity=~\"$severity\", alertname=~\"$alertname\"}))\nor\n(count by (namespace) (ALERTS{namespace=~\"$namespace\", alertstate=\"firing\", severity=\"warning\", severity=~\"$severity\", alertname=~\"$alertname\"}))",
     "legendFormat": "{{alertname}}"
    }
   ]
  }
 ]
}