{
 "title": "Pull Request Activity",
 "tags": [ "github-stats" ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "period",
    "label": "Period",
    "query": "SELECT t.__value, t.__text FROM (   SELECT DISTINCT      period as __value,     case period        when 'h24' then '24 hours moving average'        when 'd' then 'Daily'       when 'd7' then '7 days moving average'       when 'w' then 'Weekly'       when 'm' then 'Monthly'       when 'q' then 'Quarterly'       when 'y' then 'Yearly'     end as __text,      case period        when 'h24' then 1       when 'd' then 2       when 'd7' then 3       when 'w' then 4       when 'm' then 5       when 'q' then 6       when 'y' then 7     end as ordering   FROM      pr_activity    ) as t   ORDER BY t.ordering"
   },
   {
    "name": "repo",
    "label": "Repository",
    "query": "SELECT DISTINCT repo FROM pr_activity"
   },
   {
    "name": "proposed_by",
    "label": "Proposed By",
    "query": "SELECT DISTINCT proposed_by FROM pr_activity"
   }
  ]
 },
 "panels": [
  {
   "title": "Pull Request Activity ($period)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  sum(opened) AS \"Proposed\",\n  sum(merged) AS \"Merged\"\nFROM\n  pr_activity\nWHERE\n  $__unixEpochFilter(time) AND\n  period = '${period}' AND\n  repo IN(${repo}) AND\n  proposed_by IN(${proposed_by})\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Proposed Pull Requests / Group ($period)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  proposed_by,\n  sum(opened)\nFROM\n  pr_activity\nWHERE\n  $__unixEpochFilter(time) AND\n  period = '${period}' AND\n  repo IN(${repo})\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Merged Pull Requests Proposed By ($period)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  proposed_by,\n  sum(merged)\nFROM\n  pr_activity\nWHERE\n  $__unixEpochFilter(time) AND\n  period = '${period}' AND\n  repo IN(${repo})\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Pull Requests Closed With Unmerged Commits ($period)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  sum(closed_with_unmerged_commits) AS \"Count\"\nFROM\n  pr_activity\nWHERE\n  $__unixEpochFilter(time) AND\n  period = '${period}' AND\n  repo IN(${repo}) AND\n  proposed_by IN(${proposed_by})\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}