{
 "title": "Grafana Tempo GitHub Stats",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "repo", "query": "tempo,loki" }
  ]
 },
 "panels": [
  {
   "title": "Open issues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(repo_stats.$repo.repo.open_issues_count, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Open issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 28 }
   ]
  },
  {
   "title": "Open issues difference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 28 }
   ]
  },
  {
   "title": "GitHub Stars",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(repo_stats.$repo.repo.stargazers, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "GitHub Stars",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 31 }
   ]
  },
  {
   "title": "GitHub Stars Difference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 31 }
   ]
  },
  {
   "title": "Repo  Watchers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(repo_stats.$repo.repo.watchers, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "GitHub watchers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 44 }
   ]
  },
  {
   "title": "Watchers difference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 44 }
   ]
  },
  {
   "title": "GitHub forks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(repo_stats.$repo.repo.forks, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Repo forks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 35 }
   ]
  },
  {
   "title": "Forks difference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 35 }
   ]
  },
  {
   "title": "Repo Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(repo_stats.$repo.repo.size, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Repo Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 41 }
   ]
  },
  {
   "title": "Repo Size (diff)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 41 }
   ]
  },
  {
   "title": "Github API requests / 1h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(summarize(repo_stats.$repo.octokit_request_count, '1h', 'sum', false), 'Github requests')"
    }
   ]
  },
  {
   "title": "Github search usage % of limit ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "alias(summarize(repo_stats.$repo.usage_search, '1h', 'avg', false), 'Search Limit')"
    },
    {
     "target": "alias(summarize(repo_stats.$repo.usage_core, '1h', 'avg', false), 'Core Limit')"
    }
   ]
  }
 ]
}