{
 "title": "Grafana Gardening Week",
 "time": { "from": "2020-11-09T00:00:00.000Z", "to": "2020-11-15T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Open issues and PRs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.repo.open_issues_count, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Open issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 28 }
   ]
  },
  {
   "title": "Open issues difference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 28 }
   ]
  },
  {
   "title": "Open bugs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.type_bug.gauge, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Open Bugs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 23 }
   ]
  },
  {
   "title": "Open bugs Difference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 23 }
   ]
  },
  {
   "title": "Open docs issues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.type_docs.gauge, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Docs issues (last)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 41 }
   ]
  },
  {
   "title": "Docs issues (difference)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 41 }
   ]
  },
  {
   "title": "Needs investigation (avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.needs_investigation.gauge, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Needs more info (last)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Needs more info (Difference)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Open needs more info (avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.needs_more_info.gauge, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Unlabelled (last)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Unlabelled (Difference)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Open unlabelled (avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.unlabeled.gauge, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Open PRs (last)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Open PRs Change",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Open PRs (avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(gh_action.issue_query.open_prs.gauge, '$interval', 'avg', false), 2)"
    }
   ]
  },
  {
   "title": "Issues opened & closed ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(summarize(gh_action.issue.opened_count, '$interval', 'sum', false), 'Opened')"
    },
    {
     "target": "alias(summarize(gh_action.issue.closed_count, '$interval', 'sum', false), 'Closed')"
    }
   ]
  },
  {
   "title": "Closed issues by type",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(summarize(seriesByTag('name=gh_action.issue.closed_count'), '$interval', 'sum', false), 'sum', 'type'), 'type')"
    }
   ]
  },
  {
   "title": "Github API requests / 1h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(summarize(gh_action.octokit_request_count, '1h', 'sum', false), 'Github requests')"
    }
   ]
  },
  {
   "title": "Github search usage % of limit ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "alias(summarize(gh_action.usage_search, '1h', 'avg', false), 'Search Limit')"
    },
    {
     "target": "alias(summarize(gh_action.usage_core, '1h', 'avg', false), 'Core Limit')"
    }
   ]
  }
 ]
}